### ISSUE TITLE
Throw a proprietary exception when accessing Value in failed state (or Error in success state)

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#101]
Just an idea, what do you think?

I'm using a custom ExceptionFilterAttribute to catch and package various application errors into an appropriate HTTP error response for consumption by my web app.

I've found myself repeatedly checking my Results for success, and then throwing an exception on failure to pass the result error message to the filter.

However, Result already does this - attempting to access Value for a failed result throws an InvalidOperationException.

If, instead, Result threw a proprietary exception type (say, ResultFailureException) then I could skip the failure check and allow the filter to handle it with a 400 error instead of a 500.

If this sounds like a helpful change, I could submit a PR?

**Comment by vkhorikov** [comment]
A separate exception type is actually a recommended way of throwing exceptions from libraries. Merged the PR, will try to push a new version this week.
