### ISSUE TITLE
ConfigureAwait and overload resolution

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#104]
There are quite a few issues that mention or seem to imply difficulties with overload resolution (for example, #98, #64, #59, #49, #47).

And in my case, I'm often finding it necessary to specify the `continueOnCapturedContext` optional parameter in order to overcome overload resolution problems, which I find a bit ugly.

I decided to test a theory and stripped out all the `continueOnCapturedContext` optional parameters from the library. I now find that overload resolution works flawlessly throughout my code and I'll be sticking with this approach going forward.

I think it is worth dispensing with the ability to control ConfigureAwait on a per-call basis in exchange for improved usability and cleaner code both in the library and client code. Instead, we could expose a configurable property (e.g. `DefaultConfigureAwait`) that allows the user to set `ConfigureAwait(true/false)` on a global basis, so we don't lose the ability altogether.

If you think this sounds good, I can submit a PR.

**Comment by vkhorikov** [comment]
Good idea!

**Comment by space-alien** [comment]
PR submitted. It's worth noting that removing the optional ConfigureAwait param is a potentially breaking change, and that I opted for `false` as a new default rather than the current `true`. The reason it was `true` is in #53, however, the scenario mentioned [may no longer be relevant since .NET 4.6](https://stackoverflow.com/questions/45530837/why-is-the-culture-kept-after-configureawaitfalse). Anyway, I was deliberating this for a while, but since the standard advice for libraries seems to be `false`, and we're already breaking (but with the configurable property as a workaround), it seemed reasonable.

**Comment by space-alien** [comment]
Closing as this is merged.
