### ISSUE TITLE
Cosmetics - generic type names

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#110]
In some places, the generic type variable names seem a bit inconsistent. How would you feel about a purely cosmetic refactoring so that the type names are consistent throughout the library? It might help new users find it a little easier to reason about all the overloads. Something along these lines:

`T` - Current or starting result type
`E` - custom error type. Maybe nicer than being `TError`fied all the time?
`TNew` (or maybe `K`) - New result type (currently we have a mix of `K`, `TNewValue`, `TNew`, `R`, etc.)

Let me know if it sounds good, if so I'll submit a PR.

**Comment by vkhorikov** [comment]
Yep, sounds good, feel free to submit a PR.

**Comment by space-alien** [comment]
Settled on `K` for the type of new value in the end.
