### ISSUE TITLE
enhancement with int status value for Fail

### ISSUE THREAD

**Issue by ahedreville** [vkhorikov/CSharpFunctionalExtensions#122]
Hi I would request is possible to have an int Status property on the result class that could be optional set when Fail result. Is nice to have not just an string error but also an optional status int value acting such a status code for failed result

**Comment by vkhorikov** [comment]
There's a version of `Result` with two type parameters: a resulting object and an error type.

**Comment by jcsonder** [comment]
Check the unit test _Create_error_generic_argument_is_false_Failure_result_expected_ in https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions.Tests/ResultTests/ResultTests.cs: Use int instead of MyErrorClass. It's something similiar you like to have I guess.

**Comment by ahedreville** [comment]
Thanks a lot y will check such overload.
