### ISSUE TITLE
Improve Result creation

### ISSUE THREAD

**Issue by altmann** [vkhorikov/CSharpFunctionalExtensions#130]
I want to improve the creation of Result objects within this issue. 

Here my scenario:
``` c#
var result = birthdate > today ? Result.Fail("...") : Result.Ok();
```

With the current version of this lib I can simplify the code a little bit and write the following
``` c#
var result = Result.Create(birthdate <= today, "...");
```
In this scenario it would work because I changed the expression (changed > to <=) but often I want to use the failing expression because it makes more sense and its easier to read and understand. 

Because of that I want to introduce a new method in this lib:
``` c#
var result = Result.CreateFailure(failingExpression, "...");
```

- Is it okay for you? If yes I would send you the pr
- I also think about renaming the existing method: Create(...) => CreateOk(...) but then its an breaking change. Any suggestions how you want to deal about it?
- I also add the method for Result<T>, Result<T, E> and the overloaded methods for Func<> and Func<Task, ...> to be consistent with the other logic. 

Thanks in advance... :)

**Comment by vkhorikov** [comment]
Hi Michael, I'm OK with this suggestion, please go ahead with the PR. The change from `Create` to `CreateOk` would indeed be a breaking change, let's leave it as is, `Create` looks fine as a default too.

Cheers.

**Comment by altmann** [comment]
Great. A PR will come in the next days.

**Comment by vkhorikov** [comment]
Merged, thanks. Will push a new version this weekend
