### ISSUE TITLE
Add Tap for OnSuccess

### ISSUE THREAD

**Issue by golavr** [vkhorikov/CSharpFunctionalExtensions#134]
It was already mentioned in issue #16 and mitigate with void return of a method
but there are other cases like var assignment
and w/o going with the tuple nightmare suggested in #60 

```
string myValue;
...
.OnSuccess(value => myValue = value)
.OnSuccess(...)
.OnSuccess(...)
.OnSuccess(() => Foo(myValue))
...
```

i think **Tap** or **OnSuccessTap** is required, having explicit Action and returning input Result
btw tap was borrowed from [RxJS](https://rxjs-dev.firebaseapp.com/api/operators/tap) 
if it is ok with you i can start PR

**Comment by vkhorikov** [comment]
Yep, please go ahead with a PR.

BTW, tuples aren't that bad if you use the new ValueTuple syntax, e.g (string s, int i).

**Comment by stefano77it** [comment]
@vkhorikov Hi, I'm following the development of this library since taking your course on Pluralsight "Applying Functional Principles in C#", but I'm seeing recently the addition of more and more functionalities totally undocumented.

Then I'm asking: how do is supposed a new user to use this library at its full potential? For example, the new "Tap" extension, how is supposed to be discovered and understood? Reading the source code, or the examples?

I think a newcomer won't use any of the functionalities added in the last months, being undocumented.

Just my 2 cents.

stefano

**Comment by space-alien** [comment]
This looks like a really great idea, thanks for the PR.

I understand that "Tap" is borrowed from RxJS. but I wonder if it would be better for consistency if these were just OnSuccess overrides? All the new Tap methods depend on success state (of course) and I noticed that some of a few of the signatures are already covered by OnSuccess, with the same logic. 

I think it might be more consistent - and easier for new/existing library users to adopt this - if these were simply additional "OnSuccess" signatures. Also - probably easier for maintainability.

**Comment by space-alien** [comment]
Hmm, perhaps I'm being too hasty - I think my issue is with the consistency of the current OnSuccess methods.

Today, `OnSuccess` mostly carries out mapping functions, although there are a handful of `Tap`-like overrides that accept `Action` and operate on the result value where present. And we have a few Map signatures that simply pass through to OnSuccess.

Perhaps the long-term goal ought to be a more consistent API, with `Map` / `Tap` (or `OnSuccessMap` / `OnSuccessTap`) expressing the intent more clearly?

So - maybe "v2" project: Refactor towards `Map` + `Tap` which become the bread-and-butter chain methods. Existing OnSuccess signatures could be preserved for backwards compatibility. Just throwing it out there..

**Comment by golavr** [comment]
@stefano77it i agree that documentation is needed as this library gaining momentum.

@space-alien you nailed it, i think that refactoring to chain methods (Map/Tap etc.) is inevitable. you cannot express all operations in one OnSuccess signature since you'll get ambiguous/colliding errors. i guess it was started as educational library to explain the functional programming in C#.

**Comment by vkhorikov** [comment]
@stefano77it the documentation is starting to lack, indeed.

@space-alien @golavr I agree. `OnSuccess` is too bloated at this point and will benefit from the separation (with the preservation of backward compatibility).
