### ISSUE TITLE
TapIf()

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#135]
Current code:
```csharp
.OnSuccess(async () => lassie.IsGoodDog
    ? await treatService.TreatDog(
        lassie,
        reason: "Good boy!",
        // lots of other important arguments
        cancellationToken)
    : Result.Ok())
```

Would this be a useful improvement, or is there already a better way?

```csharp
.OnSuccessIf(lassie.IsGoodDog, treatService.TreatDog(
    lassie,
    reason: "Good boy!",
    // lots of other important arguments
    cancellationToken))
```

The implication being that if the condition is false, we can return the starting result.

**Comment by vkhorikov** [comment]
Looks like a good one.

**Comment by Kiba-kun** [comment]
I find an overload with `Func<T, bool>` instead of just `bool` also handy.
It will add the possibility to chain like this:
```csharp
Dog.Create("Lassie")
   .OnSuccessIf(lassie => lassie.IsGoodDog, treatService.TreatDog(
       lassie,
       reason: "Good boy!",
       // lots of other important arguments
       cancellationToken))
```
What do you think?

**Comment by space-alien** [comment]
I like that too in most cases. Hoping to look into an implementation soon. I expect there will be a lot of overloads to cover, so need to dig into it a bit..

**Comment by space-alien** [comment]
Now we have `Tap` and `Map` (#141), my gut tells me we want `TapIf`, but not `MapIf`. `MapIf` can be achieved with two calls: `Ensure` then `Map`. Combining in MapIf which will require an additional error parameter as well as the bool condition doesn't strike me as adding to readability.

Does that sound right?

**Comment by vkhorikov** [comment]
`Map` probably needs 2 input functions: one for success and the other one for failure. It would then replace both `OnSuccess` and `OnFailure`. This semantics is how F# does it with its `Result` type.

**Comment by space-alien** [comment]
I've added TapIf. I also redid the Tap tests and added async tests.

@vkhorikov I'll open a separate issue where we can look at Map.

**Comment by giangpham05** [comment]
I have been fan of this libary and I can it's improving a lot.
I landed at this issue is that I have the same feeling as @Kiba-kun 
An overload with Func<T, bool> instead of just bool also handy. I know I can use Map to achieve the task but it would be better if it has something like this: 
`var crmResult = await Task.Run
            (
                () =>
                _crmRepository.GetAsync<Product>(PluralNameConstants.Products, viewModel.ProductId, "productid", "currentcost")
                .Tap(product => _crmRepository.UpdateAsync<Product>(PluralNameConstants.Products, new Product
                {
                    Id = product.Id,
                    CurrentCost = viewModel.UnitCost
                }, product.Id))
                .Bind(product => _crmRepository.GetAsync<ProductPriceLevel>(PluralNameConstants.ProductPriceLevels, product.Id))
                .TapIf(productPriceList =>  productPriceList.Ammount != viewModel.UnitPrice,
                       productPriceList => _crmRepository.GetAsync<ProductPriceLevel>(PluralNameConstants.ProductPriceLevels, new Guid("")))
            );`
