### ISSUE TITLE
Syntax sugar for Result.Combine(...)

### ISSUE THREAD

**Issue by altmann** [vkhorikov/CSharpFunctionalExtensions#143]
Hi,

we often use this line of code which is long and hard to read

```c#
var result = Result.Combine(result, someOtherResult);
```

For example in an foreach
```c#
var result = Result.Ok();
foreach(var person in persons)
{
   var someOtherResult = await DoSomething(person);
   result = Result.Combine(result, someOtherResult);
}
```

We improved it a little bit with an extension method

```c#
var result = result.Combine(someOtherResult);
```

A more shorter option which is also semantically understandable would be this

```c#
var result += someOtherResult;
```

What do you think about operator overloading? Should I make a pr supporting this feature?

**Comment by space-alien** [comment]
Please also see #145

**Comment by golavr** [comment]
@altmann you can change it to be fully functional :), short and easy to read

```
var result = await persons
    .Select(DoSomething)
    .Combine();
```

**Comment by altmann** [comment]
Ah great. I will try it. Thanks for your answers.
