### ISSUE TITLE
Improving Map signatures

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#146]
I've been looking closely at the signatures we have for `Map()`.

The following signature looks wrong to me and I would imagine is unused. I propose removing it:
 ```csharp
// Who is going to the trouble of providing K type param to get back an untyped Result?
public static Result Map<T, K, E>(this Result<T, E> result, Func<T, Result> func)
{
    if (result.IsFailure)
        return Result.Fail<K, E>(result.Error);

    return func(result.Value);
}
```

I also wrote some code to test the mapping syntax possibilities and found the following.

Most conversions starting from `Result<T>` or `Result<T, E>` use `Func<T, Result>` for the conversion **where the `T` func param is required**. In these cases, it is not possible to use method group conversion unless the method accepts a T param. This is probably a good thing as it might reduce the risk of mistakes, such as:

```csharp
Result<TNew> NewResult() { [...] }

Result<TOld> result = Result.Ok(startingValue);

result
    .Map(NewResult) // startingValue is implicitly discarded
```

Instead, user is forced to use the lambda syntax, and think about what they are doing:
```csharp
result
    .Map(_ => NewResult()) // startingValue is explicitly discarded
```

However, there are two exceptions:
```csharp
// Inconsistent? Allows T to be implicitly discarded, when other signatures do not
public static Result<K> Map<T, K>(this Result<T> result, Func<Result<K>> func)
{
    if (result.IsFailure)
        return Result.Fail<K>(result.Error);

    return func();
}

// Inconsistent? Allows T to be implicitly discarded, when other signatures do not
public static Result<K, E> Map<T, K, E>(this Result<T, E> result, Func<Result<K, E>> func)
{
    if (result.IsFailure)
        return Result.Fail<K, E>(result.Error);

    return func();
}
```

For consistency, and the reasons above, I propose removing these signatures. I think the only impact would be (potentially misused) method group conversions, or lambda syntax such as `result.Map(() => NewResult())` which could simply be changed to `result.Map(_ => NewResult())`. The latter syntax being consistent with that imposed by the other Map signatures.

Also - given the maintenance burden - reducing the number of signatures is probably not a bad idea when the opportunity arises.

**Comment by vkhorikov** [comment]
I agree, let's remove all three.

**Comment by space-alien** [comment]
Okay, great.

I think I've found another issue:

```csharp
Result<K, E> ToResultKE() => Result.Ok<K, E>(K.Value);

result.Ok()
    .Map(ToResultKE) //or .Map(() => ToResultKE())
```
returns `Result<Result<K, E>>`

A number of the other mappings to/from `Result<T, E>` appear have the same problem. It's late now and my brain is shutting down, so I haven't considered solutions yet. Off the top of my head - a bunch more overloads for the benefit of `Result<T, E>` (argh).

My late night brain is also wondering if it's worth rethinking about making Result a class rather than a struct, to see if leveraging inheritance might allow us to cut down on the significant pain of managing these method overloads.

**Comment by space-alien** [comment]
See also #125 

Thinking aloud as usual, something like this..?

```csharp
struct Unit {}
class Result<T, E> {}
class Result : Result<Unit, string> {}
class Result<T> : Result<T, string> {}
class UnitResult<E> : Result<Unit, E> {}
```

Haven't had a chance to dig into it but my instinct tells me the codebase could be dramatically streamlined and simplified.

**Comment by space-alien** [comment]
I've revised the previous comment.
