### ISSUE TITLE
Proposal - Wrap() instead of Map(Func<T>)

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#150]
Currently, `Map()` does two different things:

1. Allows a return value `K` from a `Func<K>` or `Func<T, K>` to be wrapped in a new `Result<K>` which is then passed to the next method in the chain
2. Maps the chain onto a new Result returned by a `Func<Result>` or `Func<T, Result>`

With our current Map overloads, it is possible in some circumstances to inadvertently use (1) as follows:
```csharp
Result<T, E> DoSomething() {...}

result
   .Map(DoSomething)

/* We've now got a newly-constructed `Result<Result<T, E>>`
   and ignored whether the DoSomething result succeeded or failed. */
```

I propose that (1) should be refactored to `Wrap()` rather than `Map()` for better clarity with the current `Func<T>` signatures being marked `[Obsolete]`.

**Comment by space-alien** [comment]
Another option might be `MapValue()`. For the signatures that use `Func<T, K>` (i.e. the current `T` is the  input parameter), this might make be better semantically.

**Comment by vkhorikov** [comment]
Technically, `Func<T>` (or `Func<T, K>`) should be treated differently from `Func<Result<T>>` (or `Func<T, Result<K>>`).

In functional languages, the former is passed to `Map`, while the latter -- to `Bind` (example from F#: https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/result.fs , more explanations from Scott Wlaschin: https://fsharpforfunandprofit.com/posts/elevated-world-2/ ). I suggest that if we split `Map`, we do it the way F# does it:

- The existing `Map` should accept `Func<_, _>`, `Func<_>`, etc
- A new `Bind`  method should accept `Func<_, Result<_>>`, `Func<Result<_>>`, etc

**Comment by space-alien** [comment]
Yup, sounds good to me.

**Comment by space-alien** [comment]
[According to NuGet](https://www.nuget.org/packages/CSharpFunctionalExtensions/2.0.0), v2 has not yet been downloaded by anyone. So rather than cluttering the codebase by marking the new Map() signatures as `[Obsolete]`, I will simply rename them as `Bind()`.

**Comment by space-alien** [comment]
Done

**Comment by space-alien** [comment]
This is done - per last comment, it might be good to publish v2.1.0 as soon as poss.

**Comment by space-alien** [comment]
> [According to NuGet](https://www.nuget.org/packages/CSharpFunctionalExtensions/2.0.0), v2 has not yet been downloaded by anyone. So rather than cluttering the codebase by marking the new Map() signatures as `[Obsolete]`, I will simply rename them as `Bind()`.

A quick update: v2 now has a few hundred downloads. I guess the counters on NuGet lag a bit.

Let me know if you would prefer not breal the new `Map()` signatures like this.

**Comment by vkhorikov** [comment]
I'll push 2.1.0 now. Let's keep it as it is.
