### ISSUE TITLE
Proposal to make Result a class instead of a struct

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#151]
`Result` is currently a struct. (Actually, three structs, because of `Result<T>` and `Result<T, E>` as well.)

Unfortunately, this creates rather a lot of complications.

1. Implicit conversion operators are required to convert between the different structs, since there is no inheritance. In particular, the implicit conversions from `Result<T, E>` to `Result<T>` / `Result` actually call `ToString()` on the `E` error value, which seems rather presumptuous. Some Map() overloads rely on this conversion to get from one Result type to another, so custom errors could conceivably lose fidelity in the process.

2. The logic for creating Results is encapsulated in a special class `ResultCommonLogic`, an instance of which is then stored on every `Result`. This adds complexity and overhead. In spite of this, there is inevitably still plenty of code duplication.

3. Issue #125 highlights the requirement for a non-value `Result` with a custom error type, something that would add yet another struct to the mix, whereas a base class might be a more fitting solution.

4. There are challenges ahead with managing and improving extension overloads (see #146), some of which might be alleviated with some judicious use of class inheritance. (I am still investigating this).

I propose switching `Result` back to a class and leveraging inheritance to solve these problems. Based on my experiments so far, I think we might achieve a significant reduction in complexity, and improve maintainability.

Here are two possible approaches. Note how in both cases the base class is a new non-value result with generic `E` error type, solving #125):

**(1)** Maintain current types

```csharp
class ResultBase<E> {}
class Result : ResultBase<string> {}
class Result<T, E> : ResultBase<E> {}
class Result<T> : Result<T, string> {}
```

**(2)** This may be cleaner and more intuitive, but will break more
```csharp
class Result<E> {}
class Result : Result<string> {}
class ValueResult<T, E> : Result<E> {}
class ValueResult<T> : ValueResult<T, string> {}
```

I have started playing around with an implementation of the first approach and I am very encouraged, with complexity falling away as I progress. I still want to experiment with the second syntax though.

#99 is another (minor) issue that would be solved by this change. There are probably other benefits I haven't identified yet.

**Comment by vkhorikov** [comment]
I agree, switching `Result` to a `struct` has led to a lot of issues. The only problem I see with switching it back is the loss of non-nullability, but considering the complexity reduction, this trade-off is worth it.

I like (1) better due to backward compatibility. Also, I don't quite like the word `Value` in `ValueResult`, looks bulky.

**Comment by space-alien** [comment]
Great. I will keep working on it.

Regarding the name `ValueResult`, code probably wouldn't see it very often, except in method signatures where its explicitness might be a bonus. The rest of the time, in client code, the entry point is likely to be a static method on the `Result` class (e.g. `Create()`, `Ok()`, `Fail()` etc.) - or a chained method.

**Comment by space-alien** [comment]
@vkhorikov 
> Regarding structs vs classes. Can interfaces help?

Had the same thought - I will be investigating.

@golavr 
> but i think moving from struct to class and the loss of non-nullability is a major issue.
> isn't it one of the pillars of this library?
> struct also have the advantage of memory allocation, moving to classes might have impact on GC when dealing with lots of results.

At the moment, every `Result` instance has to create its own instance of the `ResultCommonLogic` class, so we are probably already incurring some of the performance penalties of classes. Meanwhile, the vast majority of the `Map` and `Bind` overloads return a brand new `Result`. I'm still investigating this, but I'm hoping that a `Result` class hierarchy will provide some more opportunities to simply return the starting `Result` instance via casting, avoiding lots of extra allocations.

In terms of non-nullability, are there any particular usage cases that come to mind where this is an important advantage? (For example `var results = new Result[2];` - although not sure if that's realistic.) I've only used this library in one project, I use Fody NullGuard, and now I'm starting to update code to C# 8 for nullable reference types. So I would welcome fresh perspectives to inform my thinking on this.

I'm definitely not suggesting that switching `Result` to a class is the only solution to the problems with the structs, and I hope we can explore all the possibilities, but my suspicion at the moment is that it will be the cleanest and most sustainable option.

I'll keep investigating. Next update from me will probably be next week.

**Comment by golavr** [comment]
agree that ResultCommonLogic impose performance penalties.
my take on this is that library should pay the maintainability discomfort in order to provide robust solution to users, even at the cost of violating the DRY principle.

regarding class vs struct
after enabling C# 8 and nullable you still get warning
new developers tend to ignore warnings

![image](https://user-images.githubusercontent.com/22896741/64742745-f72d3a80-d505-11e9-8ea3-2f80202b17fa.png)

with a little effort... hitting the potential fix -> **Decalre as nullable**
you unleashed the chaos

![image](https://user-images.githubusercontent.com/22896741/64742535-3a3ade00-d505-11e9-8985-866a2e3aed36.png)

**Comment by space-alien** [comment]
> agree that ResultCommonLogic impose performance penalties.
> my take on this is that library should pay the maintainability discomfort in order to provide robust solution to users, even at the cost of violating the DRY principle.

Yes, I agree!

> with a little effort... hitting the potential fix -> **Decalre as nullable**
> you unleashed the chaos

Is it reasonable for us to worry about this? If the variable is explicitly declared as nullable, then isn't the user basically saying "I'm taking responsibility for null checks on this one..." ?

**Comment by golavr** [comment]
i opened PR changing ResultCommonLogic to struct.
so now we addressed the performance issue w/o impact on the DRY, actually there is less code to maintain.

**Comment by space-alien** [comment]
@golavr Coincidentally, I worked on this yesterday as well! I took a slightly different approach - I got rid of ResultCommonLogic instances completely and put shared logic into static methods.

Having seen this, I think maybe there is merit in a "best of both" approach. I will push some code today.

**Comment by space-alien** [comment]
@golavr I've pushed a commit that incorporates your idea to refactor ResultCommonLogic to a struct along with my other DRYing efforts. I'm sorry I didn't merge your PR as it was a bit messy to try to unpick things - at least this way the change history is simpler for other reviewers.

**Comment by golavr** [comment]
@space-alien not sure i understand why you didn't accept the PR.
the code you committed contains most of the code i pushed in PR #154
the only difference (DRYing efforts) i see is in serialize/deserialize which you could add after accepting the PR or even better writing a comment in the review like i did in #145 
"it was a bit messy to try to unpick things - at least this way the change history is simpler for other reviewers" sounds like a lame excuse.
if this library wants to have community contribution than you have to learn how to chill out the eagerness to commit and deal with "bit messy" and "unpick things"

**Comment by space-alien** [comment]
I didn't mean to cause offence or to diminish your effort, and I take your point. It was just unfortunate that we worked on the same thing at the same time.

I've reopened your PR and I will try to merge it and redo my work as you suggest.

**Comment by space-alien** [comment]
@golavr Okay, I've done that. Also thank you for the tip about code commenting on the PR, I will keep that in mind in future.
