### ISSUE TITLE
[Question] Use case in a WebAPI

### ISSUE THREAD

**Issue by MYDIH** [vkhorikov/CSharpFunctionalExtensions#155]
Hi,

I got a question about how you would use `Result` in case of a WebAPI controller. This is what I've got for now :

```csharp
return await Schema.Create(input)
   .OnFailure(error => string.Format("Invalid schema received : {0}", error))
   .Ensure(async schema => (await schema.Exists(_cacheService)).IsSuccess, string.Format("Unknown schema : {0}", input.Name))
   .Ensure(schema => schema.Unique(_schemasService).IsSuccess, "A schema with the same name already exists")
   .Bind(async schema => await _schemasService.Create(schema))
   .Finally(result => result.IsSuccess
       ? (ActionResult)(Ok())
       : BadRequest(result.Error)
   );
```

Let's say that I want to return something other than a BadRequest in some cases, like a 404, How would I differentiate between failure types ? I saw the exact same question in the closed issues, I still can't understand though, please advice.

Thanks

**Comment by MYDIH** [comment]
Sorry,

Just found this : https://github.com/vkhorikov/CqrsInPractice/issues/5

I'm closing this issue

**Comment by vkhorikov** [comment]
Posted an article on this: https://enterprisecraftsmanship.com/posts/advanced-error-handling-techniques/
