### ISSUE TITLE
Source Link support

### ISSUE THREAD

**Issue by thomasdc** [vkhorikov/CSharpFunctionalExtensions#158]
Did you ever consider adding [Source Link](https://github.com/dotnet/sourcelink/) support?
It would greatly improve the debugging experience of this NuGet package.
XML documentation on the public API would also be a great addition for consumers of the package.

**Comment by vkhorikov** [comment]
I didn't know about this library. I'll have to look closer into this but it seems like a good idea.

**Comment by thomasdc** [comment]
If you want, I can create a PR.

**Comment by vkhorikov** [comment]
Please do.
