### ISSUE TITLE
Best Method to "Peek" Into a Result for Logging

### ISSUE THREAD

**Issue by solvingJ** [vkhorikov/CSharpFunctionalExtensions#16]
With Java streams we have a passive stream operation called "peek" which passes the elements un-touched to the next operation (lambda should return void):

list
.stream()
.peek(element -> log.info("element = " + element))
.map(element -> element is unscathed)

I haven't seen an equivalent in the library.  Does one exist?  If not, hard to add?  It's like ensure but returns void rather than bool?

**Comment by vkhorikov** [comment]
Yes, there is an overload for OnSuccess and OnFailure methods that accept an Action and return the previously passed result, so that you can execute some side effect in the middle of the chain. Here's one for example:

```
public static Result OnSuccess(this Result result, Action action)
{
    if (result.IsSuccess)
    {
        action();
    }

    return result;
}
```

**Comment by solvingJ** [comment]
Great answer, it actually addresses a number of other questions I have.  This makes it so simple and flexible that it will have a number of uses, particularly in integration testing.  Thanks!
