### ISSUE TITLE
Is there a "flatMap" method in the library?

### ISSUE THREAD

**Issue by solvingJ** [vkhorikov/CSharpFunctionalExtensions#17]
I searched the repo and found no reference to flatMap, but perhaps Map is overloaded with similar functionality or something.  Can you please clarify?

I am running into scenarios like this and perhaps flatMap would be the typical functional solution. 

FirstTask()
    .Map(inputObject => CreateSomeResultOfClient(inputObject))
    .Map(client => client.DoSomething())             <----Doesn't work because client is Result<Client>
    .OnSuccess(string => Console.WriteLine(string));
    .OnFailure(error => Console.WriteLine(error));

**Comment by vkhorikov** [comment]
In the library, Map is basically just for transforming a `Result<T>` into a `Result<K>`, this is not a fully-fledged Map from functional languages. Right now, there are only versions of this operation in OnSuccess and OnFailure methods. I guess what you are looking for is an overload for the OnBoth method so that the 3rd line in your sample would execute despite the previous outcome?

**Comment by solvingJ** [comment]
Indeed this would not be a canonical Flatmap either, but in this case we would want a FlatMap to expect a Result<Result<T>> and just give us the object of type T in the lambda if the inner Result was a success. I think the harder part would be that we would want an inner Fail to be handled the same as if it were a top level fail as well. 

If that doesn't make sense I can write up a proper example.

**Comment by solvingJ** [comment]
While this worked easily several times, in other cases it's throwing an exception that "There is no value for failure".

**Comment by solvingJ** [comment]
Since result.Value only works if there are no errors, I'm now using this instead: 

                .OnSuccess(result => result.Value)
                .OnFailure(error => Result.Fail(error));

Obviously this is sub-optimal for a few reasons.  Not only is it unsightly, I also think I'm losing the type in the Fail condition.  This might  not be an issue though, I'm not sure. 

Eventually I'll probably try to create FlatMap and submit a PR, if you could just let me know if you'd be willing to entertain such a PR.

**Comment by solvingJ** [comment]
It turns out that the solution was just to use OnSuccess instead of Map. 

Map should only be used if the function following it returns a value which does is not of type "Result"
