### ISSUE TITLE
Risky Tap signatures

### ISSUE THREAD

**Issue by space-alien** [vkhorikov/CSharpFunctionalExtensions#174]
**Edited 11 Mar 2020**

`Tap` always returns the starting `Result`. `Tap` can also be used on a `Func`, in which case, the return value of the `Func` is ignored.

I just ran into an issue which highlighted a problem with this approach.

Consider the following:

```csharp
int MyFunc() => 3;

Result.Success()
    // matches this overload: Result Tap<_>(this Result result, Func<_> func)
    .Tap(() => MyFunc());

    // matches this overload: Result Tap(this Result result, Action action)
    .Tap(() => { MyFunc(); });

    // since C# 7.3, matches Result Tap(this Result result, Action action)
    // before C# 7.3, compiler error due to overload resolution ("call is ambiguous")
    .Tap(MyFunc)
```

This subtle ambiguity is slightly troubling, although the consequences may not yet be problematic. But now consider what happens when we bring `Task`s into the mix:

```csharp
Task ActionTask() => Task.CompletedTask;
Task<int> FuncTask() => Task.FromResult(3);

await Result.Success()
    // matches the overload: Task<Result> Tap(this Result result, Func<Task> func)
    .Tap(ActionTask)

    // matches the overload: Task<Result> Tap<_>(this Task<Result> resultTask, Func<_> func)
    .Tap(FuncTask);
```

Disaster strikes, because `FuncTask()` is not awaited! Rather, its `Task<int>` return value is immediately discarded.

In my case, this arose because my intent was to discard the `int` result of `FuncTask`, so I reached for `Tap`.

**Workarounds:**
* Use `Tap(() => FuncTask() as Task)` - horrible.
* Use `.Tap(async () => { await FuncTask(); })` - also horrible, and vulnerable to popular code analysis tools which see the anonymous function as redundant and recommend its removal.
* Use `Map`, although this returns `Result<int>` with the value we weren't interested in.

**Permanent solutions:**
1. (My preference) Remove the `Tap` overloads that accept `Func`s. Sacrificing some convenience in exchange for explicitness and avoiding the risk of subtle and dangerous errors. Side bonus: where this breaks any existing code, it might trap inadvertent misuses. Having reviewed my own usage of `Tap` so far, I would say this change would only result in improved code quality.

2. (Need to check feasibility) Add suitable `Tap` overloads for `Func<Task<_>>` so that the compiler matches these in preference to `Func<_>`. I'm not particularly keen on this, and not sure if there's any risk of missing edge cases.

What are your thoughts?

**Comment by vkhorikov** [comment]
Apology for the late reply. I actually prefer (2) -- it's how the library solves similar issues elsewhere.

I don't have a strong opinion, though, and open to (1). Do you have examples of how removing these overloads improves code quality?

**Comment by space-alien** [comment]
I've been looking into this again. As far as I can tell so far, (1) only sacrifices the ability to use method group conversion, and even then only on `Func`s - it still works fine for voids.

So `Tap(UpdateCustomer)` would have to be rewritten `Tap(c => UpdateCustomer(c))`. But `Tap(SomeVoidAction)` is still fine.

However, the advantages of (1) seem enormous: we can remove no less than 20 Tap and TapIf overloads - and all their associated unit tests - instead of ***adding*** that same number in a bid to solve the very nasty bug with `Func<Task>` not being awaited. (And I'm not even sure this will work for users of older versions of C#, where overload resolution has not not been updated - although I haven't tested this.)

I'm going to test this on my current project to verify this analysis but let me know if you think I could be missing something on this.

**Comment by space-alien** [comment]
> I'm going to test this on my current project to verify this analysis but let me know if you think I could be missing something on this.

Done. Not a single broken method call on a big project, seems to bode well.

**Comment by space-alien** [comment]
It's done - and it's even better than I thought. I was able to remove 42 unhelpful overloads and their unit tests, that appear to do nothing but clutter and bug the library.

**Comment by space-alien** [comment]
I found the tiniest of caveats - method group conversion works less well with C# versions before 7.3 (when they improved overload resolution). But - it only seems to not work for non-async `void`s and parameterless `Func`s. And the regular lambda syntax works fine all round. Definitely not a dealbreaker for me.

**Comment by vkhorikov** [comment]
Sounds good. I'm all for removing unnecessary code.
