### ISSUE TITLE
Request to create CSharpFunctionalExtensions.Signed nuget package

### ISSUE THREAD

**Issue by petrechitashvili** [vkhorikov/CSharpFunctionalExtensions#178]
CSharpFunctionalExtensions, as of version 2.3.0, does not have a strong name / is not signed.

Can I request that you add signature to the package or create a separate signed package, if the current package needs to be unsigned?

**Comment by vkhorikov** [comment]
Please refer to this issue: https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/48
