### ISSUE TITLE
Result without Value type does not support Error types

### ISSUE THREAD

**Issue by pedromtcosta** [vkhorikov/CSharpFunctionalExtensions#182]
### My issue

The `Result` type is restricted to `string` error messages. In order to be able to use Error Types, we currently have to use the `Result<T,E>` type, but I often have the need for Error Types without the need for a return value.

Because the current `Result` does not support error types, I either have to use the error string to identify the type of the error, or use `Result<T,E>` with a dummy value that will be ignored.

Of course I understand that it's impossible to create a `Result<E>`, because it would clash with `Result<T>`.

### Suggestion

~~I suggest to create an `interface` `IError` which contains a `string Message` property, and change `Result` and `Result<T>` to use this `interface` instead of a `string` for the error property. I also think there should be a default `Error` `class` that implements `IError`.~~

~~The current `Failure(string error)` methods can still exist, as the error can be easily created from the parameter.~~

~~I can create a PR for that if the community agrees this should be implemented.~~

## EDIT

I suggest to change the order of the `T` and `E` generic parameters on the `Result<T, E>` type and replace the `T` with an `E` on the `Result<T>` type. My reasoning for that is the following:

When using the current types, if I want to have a `Result` without a `Value`, but with a `Error` which is not a `string`, I have to create a dummy class. This is not a simple overhead of creating a new type, this actually pollutes the API without something unnecessary.

Now, if we switch the order of `T` and `E`, there's the problem that if I want to have a `Result` with a `Value`, but without a "custom" `Error`, I have to explicitly make it a `Result<string, ReturnType>`

I see the second scenario as being much less harmful than the first. In the first scenario we are actually adding and exposing something that is just an implementation detail and that does not hold any business logic or value, whereas in the second one we are just making it explicit that we are using a `string` as the type of the `Result`'s error

As an extra downside to the second scenario, it breaks the previous API's contract, so I also suggest to create an `IError` `interface` so the developers get compilation errors if they decide to update the package.

**Comment by vkhorikov** [comment]
But how would you specify the type of the error even with the interface? /cc @space-alien

**Comment by pedromtcosta** [comment]
That's a good point now that I thought a bit more about it. I was thinking that the code that handles the error should cast the interface to an appropriate error type, but this has a drawback that the client code should know about the underlying type beforehand.

I am considering some other ways to implement this, as this is a feature I would really like to see in the library.

**Comment by pedromtcosta** [comment]
Maybe a solution could be to modify the `Result<T, E>` to be `Result<T, IError<E>>` and add a `Result<IError<E>>`

**Comment by vkhorikov** [comment]
Here are some existing proposals on this topic for reference: #151 #152

**Comment by pedromtcosta** [comment]
@vkhorikov I updated my suggestion on the original message

**Comment by vkhorikov** [comment]
This will be a huge breaking change, and I don't think it's worth it. As an alternative, I was thinking of introducing a `Unit` type to the library, so that `Result<E>` could be represented as `Result<Unit, E>`. Now, I don't quite like the verbosity of this solution either (having two always specify 2 type arguments), but it can probably be mitigated with the use of type aliases:
```
using MyResult = Result<Unit, MyError>;
using MyResult<T> = Result<T, MyError>;
```

Let me know if this would work or you have counter-arguments. I didn't test it.
