### ISSUE TITLE
OnSuccessTry doesn't handle async lambda

### ISSUE THREAD

**Issue by kitsu** [vkhorikov/CSharpFunctionalExtensions#183]
I've got a pre-condition followed by a try that I am translating to chained results:

``` CSharp
return await Result
    .SuccessIf(condition, "Condition error message")
    .OnSuccessTry(async () => await ThingThatMightFail, "Fail message");
```

On closing the expression Intellisense lights up saying it can't await type of `Result<Task>`. Seems like `OnSuccessTry` is missing the magic that made this work with other success methods.

`OnSuccessTry` also doesn't fit well with the new method naming scheme. Maybe change it to `TryMap` or something?

In the mean time I had to factor out the chaining:

``` CSharp
var result = Result.SuccessIf(condition, "Condition error message");
if (result.IsSuccess)
    result = await Result.Try(async () => await ThingThatMightFail, "Fail message");
return result;
```

Note that `await Try(async () => foo,` works here.

**Comment by pedromtcosta** [comment]
You can create a Task out of the condition in the first example, this way you can still use the railway-oriented approach:

```csharp
await Result
   .SuccessIf(() => Task.FromResult(condition), "")
   .OnSuccessTry(async () => await ThingThatMightFailAsync(), (e) => e.Message);
```

I am not sure if there should be an extension to create a `Task<Result>` from a `Result`, which would make your first example work, but I think there should be an overload for the `OnSuccessTry` method with a `Task` parameter instead of a `Action`, this way we wouldn't need to create a lambda with the `async` & `await` keywords

**Comment by kitsu** [comment]
The problem isn't making the top-level await work, it is that the inner-most await is not propagated. The `OnSuccessTry(async` should produce a `Task<Result>`,  but instead produces a `Result<Task>`.

I have used it extensively in multiple projects and can confirm this works everywhere else in the library. This is just one corner case that got missed.

**Comment by vkhorikov** [comment]
Please go ahead and submit a PR for the case that is missing (this will also require a usage example, so don't forget to include one).

**Comment by kitsu** [comment]
Late breaking update: while I'd love to work on this library I have at least 6 projects in the air at work and can't squeeze this in. Beside excuses I thought i'd share the work-around I just found for the missing overload in this issue. It is so obvious that I feel a little dumb not finding it earlier...

``` CSharp
return await Result
    .SuccessIf(condition, "Condition error message")
    .Bind(async () => await Result.Try(
            async () => await ThingThatMightFail, "Fail message"));
```

The `Bind` method conditionally executes a `Result` returning lambda, replacing the original in the chain. The `Result.Try` static "constructor" returns a `Result` (and correctly handles an async lambda). This code requires some ugly duplication, but avoids the need for superfluous conditionals and naming of intermediate results.
