### ISSUE TITLE
Overload for TapIf with Func<T, bool> condition

### ISSUE THREAD

**Issue by pedromtcosta** [vkhorikov/CSharpFunctionalExtensions#184]
Currently the `TapIf` extensions only accept a `bool` parameter for the condition. I think it would be convenient to also have overloads that accept a `Func<T, bool>` and `Func<T, E, bool>` for the condition. Should these overloads be added, or are there any reasons for why they're not there in the first place?

**Comment by vkhorikov** [comment]
Can you give an example of one such overload implemented?

**Comment by pedromtcosta** [comment]
Example of the overload implemented, with and without `async`:

```csharp
public static Result<T> TapIf<T>(this Result<T> result, Func<T, bool> condition, Action action)
{
    if (result.IsSuccess && condition(result.Value))
        return result.Tap(action);
    else
        return result;
}

public static async Task<Result<T>> TapIf<T>(this Task<Result<T>> resultTask, Func<T, bool> condition, Func<Task> func)
{
    Result<T> result = await resultTask.ConfigureAwait(Result.DefaultConfigureAwait);

    if (result.IsSuccess && condition(result.Value))
        await func().ConfigureAwait(Result.DefaultConfigureAwait);

    return result;
}
```
And here are the usage examples:

```csharp
Result.Success(new Customer())
    .TapIf(c => string.IsNullOrEmpty(c.Email), Do);

await Task.FromResult(Result.Success(new Customer()))
    .TapIf(c => string.IsNullOrEmpty(c.Email), DoAsync);
```

**Comment by FrancoisM** [comment]
IMO, i'd make more sense to define a Where extension and then do Where(...).Tap(...).

**Comment by pedromtcosta** [comment]
I might be missing something, but wouldn't the `Where()` method have the same behavior as `Ensure()` in this case?

**Comment by vkhorikov** [comment]
Ah, I see the use case now. Looks good. No particular reason for not implementing it, feel free to submit a PR.

A `Where` extension wouldn't work here because it would loose the context of what needs to be done with the incoming result.

**Comment by pedromtcosta** [comment]
I will start working on that and should submit the PR on the weekend.

I am considering in which of these 2 is a better way to implement these methods:
```csharp
if (result.IsSuccess && condition(result.Value))
    action();

return result;
```

```csharp
if (result.IsSuccess && condition(result.Value))
    return result.Tap(action);
else
    return result;
```

Personally, I like the second one better because on the first implementation, the logic of `Tap` is totally duplicated. On the other hand, the second example will check if the result is successful twice.

Do you have any preferences on that?

**Comment by space-alien** [comment]
Off the top of my head: `TapIf()` calls into `Tap()` we can further avoid duplication by just passing the `Func<T, bool>` return value straight into `TapIf()`. Should also make it a one-liner per overload (at least the non async methods):

```csharp
public static Result<T> TapIf<T>(this Result<T> result, Func<T, bool> condition, Action action)
    => result.TapIf(condition(result.Value), action);
```

**Comment by pedromtcosta** [comment]
Yes, I saw this in the current `TapIf()` implementation, but it wouldn't work in this case because if the result is not a success, an exception will be thrown when trying to get the `Value` property.

It's still possible to make it a one-liner on the non async methods by checking the `IsSuccess` property though:

```csharp
public static Result<T> TapIf<T>(this Result<T> result, Func<T, bool> condition, Action action)
    => result.TapIf(result.IsSuccess && condition(result.Value), action);
```

I think this is the way to go, even though it makes the condition that checks the `IsSuccess` property inside the `Tap()` method redundant in this case

**Comment by space-alien** [comment]
Ah yes, of course.

So I think your original preferred (second) option may be best after all; it is the most consistent with the approach taken on other extension methods with many signatures (i.e. keep the implementations similar to each other and as clear as possible, to help with maintainability).

```csharp
if (result.IsSuccess && condition(result.Value))
    return result.Tap(action);
else
    return result;
```

**Comment by vkhorikov** [comment]
Agree with @space-alien , no need for economizing line count, your second original option is the most readable one.

**Comment by pedromtcosta** [comment]
Great! I started implementing the overloads. I am currently writing the Unit Tests, do you have any feedback on this one?

```csharp
[Theory]
[InlineData(true)]
[InlineData(false)]
public void TapIf_T_executes_action_based_on_func_and_returns_self(bool value)
{
    Result<K> result = Result.Success(K.FromBool(value));
    bool actionExecuted = false;
    Func<K, bool> condition = k => k.Value;
    Action action = () => actionExecuted = true;

    var returned = result.TapIf(condition, action);

    actionExecuted.Should().Be(value);
    result.Should().Be(returned);
}
```

```csharp
protected class K
{
    public bool Value { get; }

    private K(bool value)
    {
        Value = condition;
    }

    public static K FromBool(bool b)
    {
        return new K(b);
    }
}
```

The reason behind the `K` class is to be able to use it as a Value for the Result, so I can test that this value is correctly passed as an argument to the `Func<T, bool> condition`

**Comment by vkhorikov** [comment]
This could have probably worked with a plain `bool` instead of `K`, but this is fine too. Merged the PR.

**Comment by space-alien** [comment]
Please take a look at #188 and #174
