### ISSUE TITLE
BindWithTransactionScope<T, K, E> missing

### ISSUE THREAD

**Issue by mnissl** [vkhorikov/CSharpFunctionalExtensions#193]
I assume the following overload is missing in BindWithTransactionScope.cs:

```cs
public static Result<K, E> BindWithTransactionScope<T, K, E>
  (this Result<T, E> self, Func<T, Result<K, E>> f)
    => WithTransactionScope(() => self.Bind(f));
```

I'm trying to transform the follwing code using CSharpFunctionalExtensions:

```cs
using var scope = new TransactionScope();

if (condition1) {
  _repository.UnitOfWork.SaveChanges();
}
if (condition2) {
  doSomething();
  _repository.UnitOfWork.SaveChanges();
}
if (condition3) {
  doSomethingElse();
  _repository.UnitOfWork.SaveChanges();
}

scope.Complete();
```

`SaveChanges()` returns `Result<int, MyException>`.

I started with:

```cs
var result = Result.Success<int, MyException>(0);
result.BindWithTransactionScope();
```

... but found no matching overload.

Without TransactionScope, I also had to reach out to the <T, K, E> overload of `Bind()`:

```cs
if (condition1) {
  result = result.Bind(_ => _repository.UnitOfWork.SaveChanges());
}
```

Hence I was wondering why there is no <T, K, E> overload for `BindWithTransactionScope()`.

**Comment by vkhorikov** [comment]
Apology for the late reply. No particular reason. Merged your pull request, thanks.
