### ISSUE TITLE
Better Debugging Experience

### ISSUE THREAD

**Issue by VladimirMakaev** [vkhorikov/CSharpFunctionalExtensions#194]
Hi I'm having great time using this library. One thing I've noticed as a potential enhancement is to either have ```ToString()``` method overridden or have a ```[DebuggerTypeProxy(...)]``` attribute applied to ```Result<...>``` types. That would make debugging much more pleasant.

Would you be interested in contribution in this area? Which approach would you like to follow?

**Comment by vkhorikov** [comment]
I like the idea and I think we already have `ToString()` overridden in `Maybe`. How would you like to override `ToString()` in `Result` ?

**Comment by VladimirMakaev** [comment]
Conceptually something like that
for Result<T,E>:
```c#
        public override string ToString()
        {
            return IsSuccess ? $"Success({Value})" : $"Failure({Error})";
        }
```
for Result<T>

```c#
        public override string ToString()
        {
            return IsSuccess ? $"Success({Value})" : $"Failure";
        }
```
I can performance optimize it to get rid of allocations on each call if it's OK conceptually.

**Comment by vkhorikov** [comment]
Merged the PR. The optimization is optional. If it reduces readability, I would rather keep the code as it is.
