### ISSUE TITLE
Extension for overriding current result only in case of failure

### ISSUE THREAD

**Issue by pedromtcosta** [vkhorikov/CSharpFunctionalExtensions#197]
I came across a scenario where I had to execute 2 operations that take the same parameter, so I could chain them with `Tap()` and `Bind()`:

```csharp
_myObject.GetSomeObject() // let's say this returns a simple Result<SomeObject>
	.Tap(so => _myObject.DoSomething(so))
	.Bind(so => _myObject.DoSomethingElse(so));
```

The problem here is that I want the whole operation to fail if `_myObject.DoSomething(so)` fails, but I cannot `Bind()` the result that comes from `_myObject.DoSomething(so)` because it returns a simple `Result`, instead of `Result<SomeObject>`, and I still need to use the value returned from `_myObject.GetSomeObject()` on the following `_myObject.DoSomethingElse(so)` call.

One solution for it would be to make `_myObject.DoSomething(so)` return `Result<SomeObject>`, but this would mean having a return type for the sole purpose of being able to chain the execution in a single specific scenario, so I don't like this idea.

I suggest creating another extension (which the name I don't know yet), that would basically work as a "TapBind", where it would "Tap" in case of success, and "Bind" in case of failure. Then I could chain the operations like this:

```csharp
_myObject.GetSomeObject() // let's say this returns a simple Result<SomeObject>
	.TapBind(so => _myObject.DoSomething(so))
	.Bind(so => _myObject.DoSomethingElse(so));
```

Do we have something that works like that currently in the library? In case not, I can start working on that if you agree this is a helpful extension to the library

**Comment by Badabum** [comment]
You can simply write your own extension method that has this behavior.

**Comment by pedromtcosta** [comment]
@Badabum yes, that's what I've done. What I am suggesting is to add this to the library

**Comment by Badabum** [comment]
I don't think it's very relevant to the library. `Tap in case of success and Bind in case of failure` - is not intuitive(at least to me) semantic that is caused purely by not wanting to provide return value of your method `DoSomething`. What you really want to do here is smth like this `Bind(input => DoSomething(intput).Map(() => input))`. Here you explicitly say that you don't care about return value of `DoSomething` but you do care about the result of the operation.

**Comment by space-alien** [comment]
Please see #181 / #189 - this had in fact already been implemented in `Tap()` and the behaviour has now been renamed to `Check()`
