### ISSUE TITLE
Awaiting Tasks in parallel

### ISSUE THREAD

**Issue by pstephenson02** [vkhorikov/CSharpFunctionalExtensions#199]
My colleagues and I recently got into a discussion after realizing that all (?) of the overloads for `Task<Result<T>` end up calling `await` on the Task before acting. The question became: if we wanted to build Tasks and subsequently run them in parallel down inside of a nested lambda for example, how could we accomplish that? For example:

```csharp
public static async Task Main()
{
  Sleep(5000)
    .Bind(four => Sleep(4000)
      .Bind(three => Sleep(3000)
        .Bind(two => Sleep(2000)
          .Bind(async one =>
          {
            // All Tasks to finish in 5000ms
            await Task.WhenAll(one, two, three, four);
            return Result.Ok();
          }))));
}

private static async Task<Result<int>> Sleep(int ms)
{
  Console.WriteLine("Sleeping for {0} at {1}", ms, Environment.TickCount);
  await Task.Delay(ms);
  Console.WriteLine("Sleeping for {0} finished at {1}", ms, Environment.TickCount);
  return Result.Ok(ms);
}
```

This doesn't actually compile but I think it demonstrates the spirit of the question.

Thank you in advance!

**Comment by vkhorikov** [comment]
I don't recommend doing this via extensions. Use plain variables instead, it's easier to read:

```csharp
Task<Result> one = Sleep(100);
Task<Result> two = Sleep(200);
Task<Result> three = Sleep(300);

Result[] all = await Task.WhenAll(one, two, three);

return Result.Combine(all);
```

**Comment by pstephenson02** [comment]
Thanks for the quick response 👍 - Agreed this does seem like the simpler, more readable approach.
