### ISSUE TITLE
Implicit conversion from T to Result<T>

### ISSUE THREAD

**Issue by JvSSD** [vkhorikov/CSharpFunctionalExtensions#201]
I find myself writing a lot of boilerplate like `return Result.Success(new T());` Because methods that return a `Result<T>` conceptually really return a `T` or a failure, it makes a lot of sense to be able to write `return new T();` on the success branches of those methods. Therefore and because it is safe, I propose to add an implicit conversion from a `T` to a `Result<T>`:

`public static implicit operator Result<T>(T value) => Result.Success(value);`

**Comment by kevinha** [comment]
Also similar implicit conversions to `Result<T,E>` would be appreciated.

**Comment by vkhorikov** [comment]
Good idea. Please go ahead with a PR. A similar conversion for `Result<T,E>` would be good too.
