### ISSUE TITLE
Q: Is there a recommended way to Map Result<T1, E1> to Result<T2, E2> ?

### ISSUE THREAD

**Issue by mmisztal1980** [vkhorikov/CSharpFunctionalExtensions#205]
As title says, I'm currently modelling a process where I need to change both the Result's value type and it's error type.

@vkhorikov is there a recommended way to handle such scenarios? Or should I implement my own extension that has something like `Func<E1, E2> antecedentErrorMapper` ?

**Comment by vkhorikov** [comment]
I don't think there is such an extension.
