### ISSUE TITLE
Proposal: implicit conversion from E to Result<T, E>

### ISSUE THREAD

**Issue by hankovich** [vkhorikov/CSharpFunctionalExtensions#209]
Implicit conversion from `T` to `Result<T>`/`Result<T, E>` is already available. However it's still impossible to omit `Result.Failure<T, E>(e)` expressions because there's no implicit conversion from E to Result<T, E>.

Note: it'll be a breaking change and such code will not compile anymore:
```csharp
Result<int, int> Foo()
{
    return 42;
}
```

But I think the case when typeof(T) == typeof(E) is pretty rare.

**Comment by vkhorikov** [comment]
I agree, that's a good idea.

**Comment by vkhorikov** [comment]
Published in v2.9.0
