### ISSUE TITLE
Calling .Combine() and getting its value on a Result leads to multiple enumeration

### ISSUE THREAD

**Issue by JvSSD** [vkhorikov/CSharpFunctionalExtensions#215]
I've noticed during debugging an application that uses ``Result<T>`` extensively that calling ``.Combine()`` and getting the produced value on a ``Result`` leads to multiple enumeration of the code that produces the ``IEnumerable<Result<T>>`` for which the ``.Combine()`` is called.

This can lead to significant unnecessary performance degradation. In my particular case, the time it takes for the routine that uses the ``Result``s and ``.Combine()`` extensively (nested, leading to even more than two rounds of iterations), goes from well over 2 minutes to under a minute.

The fix is actually rather simple: Make sure the input is enumerated before calling the actual implementation of ``.Combine()``. I'll be opening a pull request for this shortly: #216.

**Comment by vkhorikov** [comment]
Published 2.11.0
