### ISSUE TITLE
Proposal: include Error in failed result exception.

### ISSUE THREAD

**Issue by freever** [vkhorikov/CSharpFunctionalExtensions#218]
In the likely event that there is a bug in my code and I try to access a Value where there is none, I get "You attempted to access the Value property for a failed result. A failed result has no Value", which is fine, but it means I get crash reports like the following:

![image](https://user-images.githubusercontent.com/2269624/88890961-a835e400-d242-11ea-8963-d91b7f95ee56.png)

If I just knew what the error was it would save a lot of time in tracing the issue. Would you be open to changing the exception message to something like: "You attempted to access the Value property for a failed result. A failed result has no Value. The Error was [result error message]"?

Happy to submit a PR.

**Comment by vkhorikov** [comment]
Yes, good idea, please go ahead with the PR.

**Comment by freever** [comment]
Great, I think I will need permission to push my branch?

**Comment by vkhorikov** [comment]
No need to push, create a pull request.
I can change the error message myself if there are issues with the PR, let me know.

**Comment by freever** [comment]
I think I managed to do the PR - not really familiar with contributing to
public repos so this is a bit of a noob experience for me :)

**Comment by vkhorikov** [comment]
No worries. Merged the changes, they will be published in 2.11.3 soon.

**Comment by freever** [comment]
Closed by #222
