### ISSUE TITLE
IResult<out T> interface

### ISSUE THREAD

**Issue by JvSSD** [vkhorikov/CSharpFunctionalExtensions#220]
I have encountered a use case for covariance in the return values of a method that needs to return a Result with a value. For this I'd need an IResult<out T> akin to IValue<out T>. In fact, it would just need to implement both IResult and IValue<out T> and Result<T> would have to implement IResult<T>. I'll open a pull request shortly: #221.

**Comment by vkhorikov** [comment]
Merged. For historical/documentation purposes, could you post more details about the use case that needs covariance?

**Comment by JvSSD** [comment]
It basically comes down to having two classes, let's call them Derived1 and Derived2, that both derive from the same base class, Base. What I have is a factory method making a choice between calling a factory method that creates a Derived1 (or a failure) and a Derived2 (or a failure).

**Comment by vkhorikov** [comment]
Thanks, closing this issue.
