### ISSUE TITLE
Caching of hash values for ValueObject

### ISSUE THREAD

**Issue by yakimovim** [vkhorikov/CSharpFunctionalExtensions#228]
What do you think about caching the result of the calculation GetHashCode method for ValueObject? As this object should be immutable, it should be rather safe. On the other hand, it should improve performance in scenarios where a lot of calculations of hash codes involved.

**Comment by vkhorikov** [comment]
I'm fine with that. If you have a use case where this optimization is useful, feel free to submit a PR.

**Comment by JvSSD** [comment]
I think this can be closed: https://github.com/vkhorikov/CSharpFunctionalExtensions/pull/230

**Comment by yakimovim** [comment]
Yes.

**Comment by banarualexandru** [comment]
Hey there
Seems that caching of the Hashcode is not a good practice
Or at list with the current implementation.
https://rules.sonarsource.com/csharp/RSPEC-2328

**Comment by yakimovim** [comment]
@banarualexandru , we don't actually use mutable fields here. The field we use for hash caching is calculated only once and then is never changed. This is why it is OK to use it in GetHashCode implementation.

**Comment by vkhorikov** [comment]
Yep, this is fine because value objects are immutable.

**Comment by banarualexandru** [comment]
Ok, it's clear now.
