### ISSUE TITLE
Similar extensions for TypeScript?

### ISSUE THREAD

**Issue by xplatsolutions** [vkhorikov/CSharpFunctionalExtensions#231]
Before I start implementing some of these concepts in my GraphQL Nodejs TypeScript project I thought to just throw it out there if some kind of similar types exist and I can't find it :)

Great package! Thanks. Used it extensively in C# .NET Core projects.

**Comment by vkhorikov** [comment]
I'm not aware if any similar projects exist for TypeScript.

**Comment by xplatsolutions** [comment]
Thanks :)
