### ISSUE TITLE
Utilize C# 9 Record types for Value Objects

### ISSUE THREAD

**Issue by bradyclifford** [vkhorikov/CSharpFunctionalExtensions#238]
Has there been any thought into how or should we utilize the new [Record type](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types) from C#9 to represent a Value Object?

**Comment by vkhorikov** [comment]
I haven't worked with record types yet, but they look like an alternative to the ValueObject.

**Comment by bradyclifford** [comment]
Thanks for the article about this topic.  It was helpful.
