### ISSUE TITLE
Provide option for .Combine() to condense the error messages

### ISSUE THREAD

**Issue by JvSSD** [vkhorikov/CSharpFunctionalExtensions#240]
I have a lot of cases of the following structure: `input.Select(x => Transform(x)).Combine()`, where Transform returns a `Result<T>`. Often, it will return the same failure for multiple elements in `input`. We're logging those failures, often leading to log messages like the following:
`
Timestamp [ERR] Error during.... . Message: 'Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message, Something went wrong and is being concatenated into a repeated message'.
`

This is not particularly helpful for us, being hard to read and wasting space. What I would like is an option for `.Combine()` that would instead lead to something like:
`
Timestamp [ERR] Error during.... . Message: 'Something went wrong and is being concatenated into a repeated message (8x)'.
`

However, I'm not sure what the preferred way to implement this would be, so I'm holding off on a PR for now. Any thoughts?

**Comment by vkhorikov** [comment]
I think say this can be the default behavior for `Combine()` (i.e no additional option needed). Don't see any use case where such repetition is helpful.

**Comment by vkhorikov** [comment]
Merged, thanks! Should be available in 2.13.0.
