### ISSUE TITLE
ValueObject - equality comparison of parent-to-child values

### ISSUE THREAD

**Issue by petrechitashvili** [vkhorikov/CSharpFunctionalExtensions#248]
Would it be a good idea to consider making values of `MoneyWithCurrency` and `MoneyInUSD` equal in the following scenario:

```csharp
void Main()
{
	if (new MoneyWithCurrency(100, "USD") != new MoneyInUSD(100))
	{
		throw new InvalidOperationException("Both are equal to 100 USD");
	}
}

public class MoneyWithCurrency : ValueObject
{
	public MoneyWithCurrency(decimal amount, string code)
	{
		Amount = amount;
		Code = code;
	}

	public decimal Amount { get; }
	public string Code { get; }

	protected override IEnumerable<object> GetEqualityComponents()
	{
		yield return Amount;
		yield return Code;
	}
}

public class MoneyInUSD : MoneyWithCurrency
{
	public MoneyInUSD(decimal amount) : base(amount, "USD")
	{

	}
}
```

**Comment by vkhorikov** [comment]
Usually, people define 2 value objects because they want to take advantage of strong typing, which means they don't want 2 instances of different value objects to be considered equal.

In your scenario, I think it would be better to define a factory method instead of a separate class, like so:

```
public class MoneyWithCurrency : ValueObject
{
	public MoneyWithCurrency(decimal amount, string code)
	{
		Amount = amount;
		Code = code;
	}

	public decimal Amount { get; }
	public string Code { get; }

	protected override IEnumerable<object> GetEqualityComponents()
	{
		yield return Amount;
		yield return Code;
	}

	public static MoneyWithCurrency CreateMoneyInUSD(decimal amount)
	{
		return new MoneyWithCurrency(amount, "USD");
	}
}

```

**Comment by petrechitashvili** [comment]
I'd like to state that a method returns a `MoneyInUSD`, not `MoneyWithCurrency`, basically for clarity.

What about something like this:

```csharp
[Serializable]
public abstract class ValueObjectWithDescendantEquality : ValueObject
{
    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        
        var thisType = GetUnproxiedType(this);
        var objType = GetUnproxiedType(obj);

        if (!thisType.IsSubclassOf(objType) && !objType.IsSubclassOf(thisType))
            if (GetUnproxiedType(this) != GetUnproxiedType(obj))
                return false;

        var valueObject = (ValueObject) obj;

        return GetEqualityComponents().SequenceEqual(valueObject.GetEqualityComponents());
    }
}
```

**Comment by vkhorikov** [comment]
What's the purpose of having 2 value objects in this use case, given that you want their instances to be mutually comparable? Looks like just 1 VO (`MoneyWithCurrency`) is enough?

**Comment by petrechitashvili** [comment]
> What's the purpose of having 2 value objects in this use case, given that you want their instances to be mutually comparable? Looks like just 1 VO (`MoneyWithCurrency`) is enough?

Consider these two method signatures:

```csharp
public MoneyWithCurrency GetMoney() ...
```

versus

```csharp
public MoneyInUSD GetMoney() ...
```

I'd argue that the second signature communicates the intent that the result **has to be** in USD, whereas the first signature leaves that intention up for interpretation and requires more involvement on the programmer's part.

Besides, `MoneyInUSD` limits what has to be returned from the method and eliminates the possibility of returning anything other than that specified in the signature. I don't think this makes it more honest but I do think it makes it more clear.

These is a subtle nuance, I understand that, but hey, why not? 🙂

Happy New Year to you, Vlad!

**Comment by vkhorikov** [comment]
Happy New Year to you too! :)

Regarding the two value objects. The second signature is clearer, but so is this one:

```csharp
public MoneyWithCurrency GetMoneyInUSD() ...
```

This does leave room for issues where you accidentally return a non-USD currency, but still, I don't it's a good reason to introduce a separate VO. Different VO types work best when you want to segregate different domain concepts. Here, the concept is the same, just with different content. The separate VO in this situation would be similar to having separate classes for all of these properties: https://github.com/vkhorikov/DddInAction/blob/master/DddInPractice.Logic/SharedKernel/Money.cs#L10-L16

**Comment by petrechitashvili** [comment]
Okay, I'll take that, thank you.

I have a fork of this repo/project that I strongly-sign and have done these proposed modifications in it anyway 🙂

Matter closed.
