### ISSUE TITLE
Upgrading from 2.13.0 to 2.13.1 gives us compile-time errors

### ISSUE THREAD

**Issue by JvSSD** [vkhorikov/CSharpFunctionalExtensions#249]
During an upgrade of some internal software, we got some `ArrayTypeMismatchException` during a call of a method in a nugetted internal library. After some day's worth of trial and error of two people, we managed to pinpoint the error to upgrading the CSharpFunctionalExtensions package we're using from 2.13.0 to 2.13.1. I I was baffled at this, but using version 2.13.0 we really don't get the error and using 2.13.1 (or 2.13.2) we do.

Having determined this, I could try the upgrade in the library project itself, which finally explained why this was happening: 2.13.1 gives us compile-time conversion errors. In condensed for, it says 'Cannot implicitly convert Result<T> to IResult<T>'.  It tried to perform this at runtime for an array of these, giving us this then-baffling error.

Next, I will try to reproduce it from within this library.

**Comment by JvSSD** [comment]
Okay, that was easy. Apparently I hadn't found the [actual commit page](https://github.com/vkhorikov/CSharpFunctionalExtensions/commit/12770a82c018a3401ee2cafacec86cf9ff4659c4) yet. This shows the part very relevant for us:

![image](https://user-images.githubusercontent.com/54601698/101799761-d38fe000-3b0c-11eb-8a02-bedc5ab7d01a.png)

We're using `IResult<T>` analogous to `Result<T>` (using the interface for the use of covariance), not as an `IResult<E>`. So it is clear that this change is breaking for us and the spirit of https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/220.

**Comment by vkhorikov** [comment]
I had to add this to implement proper implicit conversions for dynamics. Any chance that you can update the use of `IResult<T>` to `IResult<T,string>`?

If you have any other suggestions that would preserve the logic of `ImplicitConversionTests`, let's discuss.

**Comment by JvSSD** [comment]
I have both both tests and my use case working. However, I can still see a few issues remaining with the conversions (that really already existed before). These come down to how we want to handle any `IResult`: Do we want to allow these to be wrapped in another `IResult`? IMO, that does not make all that much sense, but then we also have to handle what to do when a consumer of the library wants to convert, say, an `IResult<T>` to an `IResult<T, E>`. Maybe we could add explicit conversions that could fail for those cases where such a `Result<T, E>` cannot be constructed due to insufficient data (like a failed `Result<T>` to `IResult<T, E>`)?

**Comment by vkhorikov** [comment]
This can probably be mitigated by removing `IResult<E>` from the library altogether (`IResult<T, E>` itself should be enough). Made the change, all tests are passing: https://github.com/vkhorikov/CSharpFunctionalExtensions/commit/743ae6d95999f65210df4ba575496225f3845999

Let me know if this works for you ( https://github.com/vkhorikov/CSharpFunctionalExtensions/tree/iresult branch), I will merge to master if it does.

**Comment by JvSSD** [comment]
Not quite, I need the `IResult<out T>` back. The `IError<out E>` helps a lot to simplify letting the tests still pass, I see. I've created a pull request that should re-add it (which includes a few tests to guard for the `Result<T> : IResult<out T>` and the latter's covariance).

**Comment by vkhorikov** [comment]
Did a small refactoring, take a look: https://github.com/vkhorikov/CSharpFunctionalExtensions/pull/252/commits/8b97010e54feeceea63c2102bcd01b9a73386c0d The major change is
```csharp
    public interface IResult<out T> : IResult, IValue<T>
    {
        string Error { get; }
    }
```
==>
```csharp
    public interface IResult<out T> : IResult<T, string>
    {
    }
```

**Comment by JvSSD** [comment]
Sure. For me, the current code should be fine. I'm still wondering about cases like the one below, though:

```
dynamic value = new MyType();
dynamic result = Result.Success<MyType>(value);

var cast = (Result<string, dynamic>)result;
```
This results in a `Failure(Success(MyType))`. I'd rather expect at least a `Success(Success(MyType))`, or in this case something like a `Success(MyType, dynamic)` or something.

The thing is, we've now built some support for certain explicit conversions, but not others. At the same time, we're running this through the implicit operator, rather than an explicit one. I use the implicit one rather a lot, properly implicitly, in my code, though, so converting it to an explicit conversion would be bad. Any thought about dealing with these?

**Comment by vkhorikov** [comment]
Implicit operators can be used as explicit (like in your example). It's the only way to use them with dynamis.

The reason this sample results in `Failure(Success(MyType))` is because `Result<MyType>` is not compatible with `Result<string, object>` (`dynamic` is represented as `object` internally). In terms of covariance, `MyType` (`T`) is not a subclass of `string`.

This code worked for me (changed `Result<string, dynamic>` to `Result<MyType, dynamic>`):

```csharp
dynamic value = new MyType();
dynamic result = Result.Success<MyType>(value);

var cast = (Result<MyType, dynamic>)result;
```

Now it returns `Success(MyType, object)` because the covariance rules are met.

Without dynamics, there's no need to use these implicit operators explicitly.

**Comment by JvSSD** [comment]
Oh, haha, missed that while rewriting my example. As far as I am concerned, this one is good to go, then.

**Comment by vkhorikov** [comment]
Great! I'll publish these changes in v2.13.3
