### ISSUE TITLE
Name collisions

### ISSUE THREAD

**Issue by esteimanuel** [vkhorikov/CSharpFunctionalExtensions#25]
Hi Vladimir,

Currently I am trying to use your CSharpFunctionalExtensions library, but I am getting a name collision when I try to use it as follows. 
```csharp
// Given a function with a signature of Func<string, bool>.
bool IsNotNullOrWhiteSpace(string text) => !string.IsNullOrWhiteSpace(text);

// When I try to use Ensure like this.
// Then the compiler gives a error.
void MyFunction(string text) {
  Result.Ok(text)
    .Ensure(IsNotNullOrWhiteSpace, "Text is null or white space.")
}
```

Compiler warning:
> The call is ambiguous between the following methods or properties: 
'AsyncResultExtensionsRightOperand.Ensure<T>(Result<T>, Func<T, Task<bool>>, string)' 
and
'ResultExtensions.Ensure<T>(Result<T>, Func<T, bool>, string)'

```csharp
// This is possible:
void MyWorkAround(string text) {
  Result.Ok(text)
    .Ensure(t => IsNotNullOrWhiteSpace(t), "Text is null or white space.")
}
```

It is not a problem, though I prefer the cleaner look of just using the name of my expression bodied function.

I would prefer prefixing async functions with Async to explicitly state their nature and moving them to their own namespace.

If you do not have any objections I could create a pull request unless this behavior is by design? 

P.S.
I really enjoyed your PluralSight course and I am looking forward to seeing more from you in the future.

**Comment by vkhorikov** [comment]
Hi Esté. Thanks for the issue report and thanks for the nice words! :)

You can definitely create a pull request for this issue. Let me know if you have problems with it, I can look at it too.

**Comment by solvingJ** [comment]
I'll try to work on the overload for the Ensure case, however I don't support adding Async in this case.  I think it's a good idea however to add more indications about the implicit async handling on the homepage and examples.

**Comment by FrancoisM** [comment]
On the same note Resharper keeps complaining when I use
` .OnSuccess(this Result result, Action action) `
because it thinks I'm using 
`Result<T> OnSuccess<T>(this Result result, Func<T> func)`
as when I use lambda for Action to set some field value e.g 
`() => myField = myFieldResult.Value `
it thinks I meant
`() => { return myField = myFieldResult.Value;}`

**Comment by solvingj** [comment]
FYI, I don't think I ever got around to doing what I wanted, and won't for quite a while.

**Comment by FrancoisM** [comment]
too bad, suffixing with Async was the way to go.
