### ISSUE TITLE
Changing the error message for specific usages

### ISSUE THREAD

**Issue by benprime** [vkhorikov/CSharpFunctionalExtensions#250]
I'm in a situation where I have a widely-used method on a dictionary. It's very simple it tries to get a value from a dictionary, and returns "key not found in dictionary" as the error when the key is not found.
`public static Result<V> GetValue<K, V>(this Dictionary<K, V> dictionary, K key)`

However, I find myself wanting to change the error message in certain situations to provide more context. It makes me wonder if there should be an extension method, something along the lines of:
`myDictionary.GetValue(myKey).OnErrorMap(() => "New, more specific error message")`

I suppose I could use OnErrorCompensate and then create a different failed result with a new error message, but i was wondering if there was something more concise.

**Comment by vkhorikov** [comment]
Take a look at `MapError`, it should fit your use case.
