### ISSUE TITLE
Consider adding TryMap extension methods

### ISSUE THREAD

**Issue by petrechitashvili** [vkhorikov/CSharpFunctionalExtensions#265]
Currently, `Map` functions wrap the `Func<T,K>` in `Result.Success(...)`

This is problematic if the `func` raises an exception.

Please consider adding similar methods for `TryMap`ping (i.e. wrapping the func in `Result.Try(...)`)

**Comment by hankovich** [comment]
For me the proposed method sounds like a case for `Bind` (i.e. `Map` that potentially maps value to error is not actually `Map`).

How about `result.Bind(value => Result.Try(() => func(value)))` as a workaround?

**Comment by petrechitashvili** [comment]
> For me the proposed method sounds like a case for `Bind` (i.e. `Map` that potentially maps value to error is not actually `Map`).
> 
> How about `result.Bind(value => Result.Try(() => func(value)))` as a workaround?

OK, agreed.

What about TryBind instead of TryMap to avoid `Result.Try`-ing? 🙂

**Comment by vkhorikov** [comment]
@petrechitashvili The new extension looks good to me. But I think `BindTry` is a better name here: we are binding the result of an inner `Try` call, as opposed to trying (i.e. invoking a method that may throw) a `Bind` method.

**Comment by hankovich** [comment]
I'm sure the issue may be closed as implemented
