### ISSUE TITLE
Make ValueObject.CompareTo virtual

### ISSUE THREAD

**Issue by linkdotnet** [vkhorikov/CSharpFunctionalExtensions#272]
The current implementation of `CompareTo` in `ValueObject` is not `virtual`.
This isn't very handy if you use it in combination with for example NHibernate and lazy loading.

Is there an argument against chaning the method to `public virtual int CompareTo(object obj)` and `public virtual int CompareTo(ValueObject other)`?

**Comment by vkhorikov** [comment]
I'll merge the PR, thank you.

Have you actually run into this issue? When using NHibernate's `Component` feature, NH shouldn't create proxies on top of it. Though, there could be some other use cases I'm not seeing right now.

**Comment by linkdotnet** [comment]
Yes I ran into the issue:
```
Option: method CompareTo should be 'public/protected virtual' or 'protected internal virtual'
```

This happens when you have a one to many relationship with your ValueObject. (Entity owns a collection of value objects).

You are right: When you directly map it with `Component` it works. Maybe this is more a special case and could be handled with an intermediate ValueObject holding the collection.

**Comment by vkhorikov** [comment]
Ok, thanks for the clarification. Making those methods virtual wouldn't hurt either way.
