### ISSUE TITLE
Align EnumValueObject<TEnumeration, TId> and EnumValueObject<TEnumeration>

### ISSUE THREAD

**Issue by MikelThief** [vkhorikov/CSharpFunctionalExtensions#286]
Introduction of `EnumValueObject<TEnumeration, TId>` is a great addition to the set of available classes in the library.
However, I see that implementations merged in #275 are not aligned.

I would like to have similar set of properties and methods available in `EnumValueObject<TEnumeration, TId>` :
1. `public static IEnumerable<TEnumeration> All = EnumerationsById.Values;`
2. `public static bool Is(string possibleName) => EnumerationsByName.ContainsKey(possibleName);`
3. `public static bool Is(int possibleId) => EnumerationsById.ContainsKey(possibleId);`

which are present in its counterpart `EnumValueObject<TEnumeration>`.

In addition to this alignment I would like to discuss two entries that could possibly benefit from refactoring:
1. Change `possibleKey` to `possibleId` in `public static bool Is(string possibleKey) => ...` in  `EnumValueObject<TEnumeration>` since `id` parameter is present in other method's signatures. This would make overall API consistent.
2. Change return type in `public static IEnumerable<TEnumeration> All = Enumerations.Values;` to `ICollection<TEnumeration>` to better express what's really returned (one can assume that IEnumerable content here is not materialized yet imho; refering [this pos](https://enterprisecraftsmanship.com/posts/return-the-most-specific-type/)t)
3. `ToString()` called on `EnumValueObject<TEnumeration, TId>` should return rather a `Name` than an `Id` (this is questionable since this behaviour will be somewhat different from what one can expect from `EnumValueObject<TEnumeration>` where `Id` is a `string`).

I can prepare a PR if you consider these changes valid.

**Comment by vkhorikov** [comment]
Yep, the proposed changes look good. Just one minor note from me: in section 2, it's better to return an `IReadOnlyList` instead of `ICollection`.
