### ISSUE TITLE
162 methods missing async

### ISSUE THREAD

**Issue by p-bojkowski** [vkhorikov/CSharpFunctionalExtensions#288]
Hi!

just search for: static Task

Result:

![image](https://user-images.githubusercontent.com/74313141/119276162-9da56a80-bc19-11eb-9bde-5064f88c103c.png)

**Comment by Badabum** [comment]
Naming methods and functions with Async suffix is a dated convention that was actually added to .net framework to solve compatibility problems when you already have methods with a needed name but which work synchronously. There is no need to follow it in today's world and actually following it makes your code far less readable.

**Comment by vkhorikov** [comment]
I agree with @Badabum. It's best to use the `Async` suffix only when the method doesn't compile otherwise (due to name collisions).

**Comment by p-bojkowski** [comment]
I don't mean here suffixes. I mean async modifier: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/async

**Comment by vkhorikov** [comment]
Ah, I see. Those are unnecessary too if the method doesn't use the result of the inner async method. For example this method:

```csharp
public static Task<Result<T, E>> TapIf<T, E>(this Task<Result<T, E>> resultTask, bool condition, Func<Task> func)
{
    if (condition)
        return resultTask.Tap(func);
    else
        return resultTask;
}
```

Just returns the result of the `Tap` operation or the `resultTask`, whereas `Tap` needs to extract the output of the task:

```csharp
public static async Task<Result<T, E>> Tap<T, E>(this Task<Result<T, E>> resultTask, Func<Task> func)
{
    Result<T, E> result = await resultTask.DefaultAwait();

    if (result.IsSuccess)
        await func().DefaultAwait();

    return result;
}
```

**Comment by seangwright** [comment]
It's called [Eliding](https://blog.stephencleary.com/2016/12/eliding-async-await.html)

> It’s more efficient to elide async and await. By not including these keywords, the compiler can skip generating the async state machine. This means that there are fewer compiler-generated types in your assembly, less pressure on the garbage collector, and fewer CPU instructions to execute.

> However, it’s important to point out that each of these gains are absolutely minimal. There’s one fewer type, a handful of small objects saved from GC, and only a few CPU instructions skipped. The vast majority of the time, async is dealing with I/O, which completely dwarfs any performance gains. In almost every scenario, eliding async and await doesn’t make any difference to the running time of your application.

> ...

> I suggest following these guidelines:

> 1. Do not elide by default. Use the async and await for natural, easy-to-read code.
> 2. Do consider eliding when the method is just a passthrough or overload.

- Stephen Cleary
