### ISSUE TITLE
Recommendation: Maybe<T>.IfNone()

### ISSUE THREAD

**Issue by seangwright** [vkhorikov/CSharpFunctionalExtensions#294]
`Maybe<T>.UnWrap()`and `Maybe<T>.Match` are great if you want to leave the monad and operate on values, but a lot of the benefits of the monad come with the fluent chaining of operations and transformations.

Often, as a `Maybe<T>` is working its way through layers of an application, there comes a point at which a default/fallback value is known and can be provided to the `Maybe<T>` but I don't what to unwrap it.

Example:

```csharp
Maybe<string> firstName = "sean";
Maybe<string> lastName = "wright";

// How do I supply a fallback value (in the case of `Maybe<string>.None` without unwrapping, like "unknown"?
Maybe<string> fullName = firstName.Bind(f => lastName.Map(l => $"{f} {l}"));

// later on ...

// if `fullName` was empty earlier I'd like it to have had the value "unknown" so that `uniqueFullName`
// wouldn't be just a Guid
Maybe<string> uniqueFullName = fullName.Map(n => $"{n}{Guid.NewGuid()}");
```

I propose something like `IfNone()`:

```csharp
public static Maybe<T> IfNone<T>(this Maybe<T> source, T fallback)
{
    if (source.HasNoValue)
    {
        return fallback;
    }

    return source;
}
```

Or maybe it would make sense to add an overload to `Maybe<T>.Map()` that took a 2nd parameter of a fallback value?

**Comment by vkhorikov** [comment]
This is a good idea, but I'm not sure about the name of the method. I saw other libraries named it something like `OrElse`.

How about `Or`? Also, there could be 2 overloads, one for  a `T` argument and the other one for `Maybe<T>`.

As a side note, in your example, it looks like the full name will contain `None` if the first name is empty, but the last name is not. I would expect the full name to contain either both names, or one of the names if the other one is empty.

**Comment by seangwright** [comment]
> 
> 
> This is a good idea, but I'm not sure about the name of the method. I saw other libraries named it something like `OrElse`.
> 
> How about `Or`? Also, there could be 2 overloads, one for a `T` argument and the other one for `Maybe<T>`.

Is this what you're thinking?

```csharp
public static Maybe<T> Or<T>(this Maybe<T> source, T value);
```

Would the `Or` that takes a `Maybe<T>` confuse with the `Bind()` semantics? Should it include `Bind*` in the name or is it best to keep this concepts different?

Naming is hard!

> 
> As a side note, in your example, it looks like the full name will contain `None` if the first name is empty, but the last name is not. I would expect the full name to contain either both names, or one of the names if the other one is empty.

Correct, maybe (😁) not the best example.

**Comment by vkhorikov** [comment]
> Is this what you're thinking?

This implementation looks good, yes.

> Would the `Or` that takes a `Maybe<T>` be confused with the `Bind()` semantics? Should it include `Bind*` in the name or is it best to keep this concepts different?

`Bind` means that the argument will only be used if the source is not empty, which is not the case here. Just `Or` should be fine for both overloads.

> Naming is hard!

Indeed! :)

**Comment by seangwright** [comment]
Ok, I'll make a PR for this!

I'm guessing we'll want the full suite of extension overloads including additions to `AsyncMaybeExtensions.cs`?

**Comment by vkhorikov** [comment]
> I'm guessing we'll want the full suite of extension overloads including additions to AsyncMaybeExtensions.cs?

Preferrably, yes.
