### ISSUE TITLE
Id on Entity class should be private.

### ISSUE THREAD

**Issue by xavierjohn** [vkhorikov/CSharpFunctionalExtensions#302]
It is normal for domain entity class to not have an Id so making Id public exposes a property that makes no sense to the domain.

Example. StudentNumber is the key for Student entity.  It makes sense to declare the class as
```

class Student:Entity
{
      public StudentNumber;
      public Name;

      ctor(string studentNumber, string name) : base(studentNumber)
     {
         this.StudentNumber = studentNumber;
          this.Name = name;
     }
}
```

If this class was used for storage with EF, it will not try to persist Id, if Id was made private.  Having a public Id forces all domain entities to have Id which violates the domain purity.

**Comment by xavierjohn** [comment]
Your email is full.

vlad@enterprisecraftsmanship.com
Remote Server returned '552 5.2.2 Mailbox size limit exceeded 1625158722-JlfT9WQJrE-wfMG6cAk'

**Comment by vkhorikov** [comment]
> Remote Server returned '552 5.2.2 Mailbox size limit exceeded 1625158722-JlfT9WQJrE-wfMG6cAk'

This is very strange. Thanks much for letting me know, it should be working now.

**Comment by vkhorikov** [comment]
Regarding Ids. Using natural Ids (such as StudentNumber) is sub-optimal. It assumes that the identity of the student is defined by their number, which it shouldn't be. An entity shouldn't be defined by any of its properties; it should be surrogate -- something that isn't tied to the real world.
