### ISSUE TITLE
[Question] What is the purpose of Result<T> for failures?

### ISSUE THREAD

**Issue by lonix1** [vkhorikov/CSharpFunctionalExtensions#305]
A failure result cannot have a value, and attempting to access its `Value` [will throw](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/6b0b0c0da709d54b5497ee4dde22ebd680ffd574/CSharpFunctionalExtensions/Result/ResultT.cs#L17). So `Result<T>` only makes sense for success, not for failure.

So what is the point of the factory methods [`Result.Failure<T>(string error)`](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/6b0b0c0da709d54b5497ee4dde22ebd680ffd574/CSharpFunctionalExtensions/Result/Methods/Failure.cs#L16)  and [`Result<T, E> Failure<T, E>(E error)`](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/6b0b0c0da709d54b5497ee4dde22ebd680ffd574/CSharpFunctionalExtensions/Result/Methods/Failure.cs#L24).

Am I misunderstanding? Surely those factory methods are just dead code?

**Comment by lonix1** [comment]
Well I feel dumb for asking that, it's absolutely necessary.

e.g.:
````cs
public Result<User> findUser() {

  // ...happy path
  return Result.Success<User>();

  // ...error
  return Result.Failure<User>("error");     // <--- here is the reason, must match method signature
}
````

**Comment by vkhorikov** [comment]
Yep, different branches of the class.
