### ISSUE TITLE
[Question] Parameterising valueobjects for validation purposes

### ISSUE THREAD

**Issue by lonix1** [vkhorikov/CSharpFunctionalExtensions#308]
I hope there is someone who has an idea for this.

## Problem

Suppose your valueobject performs validation so it's always valid.

````cs
public class Password : SimpleValueObject<string> {

  private int _minLength = 6;
  private int _maxLength = 20;
  private bool _includeLower = true;
  private bool _includeUpper = true;
  private bool _includeNumber = true;
  private bool _includeSymbol = true;

  public Password(string value) : base(value) {
    // assume validation occurs here, using fields above
    // if invalid then throws
  }

}
````

As you can see the fields contain domain logic about what constitutes a valid password. Problems:
- they are hardcoded... yuck!
- duplication: these values are also needed elsewhere, e.g. when configuring entities with Entity Framework, or when describing metadata for Swagger APIs

## Solution 1

````cs
public static class Constants {
  public const int PasswordMinLength = 6;
  public const int PasswordMaxLength = 20;
  public const bool PasswordIncludeLower = true;
  public const bool PasswordIncludeUpper = true;
  public const bool PasswordIncludeNumber = true;
  public const bool PasswordIncludeSymbol = true;
}
````

That class can be used everywhere - by the valueobject during validation, and also by EF's configuration, and wherever else.

But:
- this feels a little dirty
- useful valueobjects (e.g. `Password`, `Email`) will probably live in a `Common` assembly, whereas the `Constants` class lives in the main assembly which houses the domain... so the valueobjects cannot see the constants

## Solution 2

````cs
public class Password : SimpleValueObject<string> {

  public const int PasswordMinLength => 6;
  public const int PasswordMaxLength => 20;
  public const bool PasswordIncludeLower => true;
  public const bool PasswordIncludeUpper => true;
  public const bool PasswordIncludeNumber => true;
  public const bool PasswordIncludeSymbol => true;

  public Password(string value) : base(value) {
    // assume validation occurs here, using properties above
    // if invalid then throws
  }

}
````

That's better as those values can now be accessed from anywhere.

But:
- they are hardcoded
- they will be hard to change, there could be assembly dependency / versioning issues depending on where these constants are used

## Solution 3

````cs
  public Password(string value, ValidationOptions options) : base(value) {
    // assume validation occurs here, using values from given options object
    // if invalid then throws
  }
````

This is more practical, as we can get parameterisations from config (e.g. `appSettings.json` or wherever).

But:
- domain knowledge has leaked out of the valueobject
- the valueobject is now dumb - it requires domain knowledge to be *given to it*... feels like bad DDD

How are other people handling this problem?

**Comment by vkhorikov** [comment]
Strongly recommend solution 2.

> they are hardcoded

Nothing wrong with values being hardcoded. In fact, hardcoding such values should be the default choice because extracting them to config files unnecessarily increases maintenance burden (http://mikehadlow.blogspot.com/2012/05/configuration-complexity-clock.html and https://enterprisecraftsmanship.com/posts/make-hard-coding-your-default-choice/ ).

> they will be hard to change, there could be assembly dependency / versioning issues depending on where these constants are used

This is true only if you compile the Domain dll separately from your solution and then copy that dll manually to the solution's bin folder, which is a bad idea anyway. In most projects, the code base is built in full on every delivery (as it should), so versioning is not an issue.
