### ISSUE TITLE
Add travis or appveyor yaml to run tests on CI server

### ISSUE THREAD

**Issue by jonny-novikov** [vkhorikov/CSharpFunctionalExtensions#31]
I suggest Appveyor for .NET projects but you can use both via git hooks

**Comment by bothzoli** [comment]
The CI pipeline with tests is running on [Azure Dev Ops](https://dev.azure.com/EnterpriseCraftsmanship/CSharpFunctionalExtensions/_build?definitionId=1) so I believe this issue could be closed.
