### ISSUE TITLE
Entity vs. EnumValueObject

### ISSUE THREAD

**Issue by p-bojkowski** [vkhorikov/CSharpFunctionalExtensions#314]
Hi :)

I just saw this class: [Industry.cs](https://github.com/vkhorikov/FuntionalPrinciplesCsharp/blob/master/New/CustomerManagement.Logic/Model/Industry.cs)  

What is the advantage of implementing "Industry" as Entity instead of EnumValueObject?

**Comment by vkhorikov** [comment]
I wrote that code when there was no EnumValueObject class. Currently, you can just use EnumValueObject.

Technically, Industry is an entity, but there's no point in introducing EnumEntity, because the 2 enums will behave almost exactly the same.
