### ISSUE TITLE
Non-generic Maybe.None

### ISSUE THREAD

**Issue by Razenpok** [vkhorikov/CSharpFunctionalExtensions#317]
Since there's now a non-generic `Maybe` class, it would be nice to have a `Maybe.None` member which could implicitly cast to a `Maybe<T>`

```csharp
public Maybe<int> GetInvalidValue()
{
    return Maybe.None;
}
```

For this change `Maybe` class will need to be changed to be non-static. Maybe change it to `struct` also, to make it consistent with `Maybe<T>`.

I can send a PR if you think this might be a good idea.

**Comment by vkhorikov** [comment]
@Razenpok Yes, please go ahead with the PR. Please also include a test that demonstrates the implicit conversion.
