### ISSUE TITLE
GetEqualityComponents

### ISSUE THREAD

**Issue by ahcruzado** [vkhorikov/CSharpFunctionalExtensions#319]
Hi Vladimir, thanks for sharing the code.
Does the GetHashCode method of the ValueObjectOfT class not use GetEqualityComponents?

Thank you

**Comment by vkhorikov** [comment]
No, there's no `GetEqualityComponents` in `ValueObject<T>`, you need to implement it manually. Use `ValueObject` (without `<T>`) for the `GetEqualityComponents` method
