### ISSUE TITLE
Feature: Extensions for IEnumerable<Maybe<T>>

### ISSUE THREAD

**Issue by seangwright** [vkhorikov/CSharpFunctionalExtensions#324]
I was wondering if there was any value in extensions like these:

```csharp
public static IEnumerable<T> MapValues<T, K>(this IEnumerable<Maybe<T>> maybes) =>
    maybes.Where(m => m.HasValue).Select(m => m.Value);

public static IEnumerable<K> MapValues<T, K>(this IEnumerable<Maybe<T>> maybes, Func<T, K> selector) =>
    maybes.Where(m => m.HasValue).Select(m => selector(m.Value));
```

I do run into situations where I have a collection of `Maybe<T>` and I want to filter to only the items in the collection that have a value and then map that value.

Currently, I use the implementation `maybes.Where(m => m.HasValue).Select(m => m.Value)`, and even though there's no other way to do it, I'd prefer not to see it in my code :)

I'm not sold on the name `.MapValues()`, but I'm not sure what would be appropriate.

**Comment by vkhorikov** [comment]
Yeah, I use `maybes.Where().Select()` a lot too. A new extension method wouldn't hurt. Regarding naming, `FilterValues` would probably be better. The method contains both filtration (`Where`) and mapping (`Select`), but I think the emphasis here should be on filtration, the mapping part is going to be obvious from the signature. I'm open for other suggestions too, though.

**Comment by Razenpok** [comment]
A new extension method would be great indeed, through you can currently use `.Choose(x => x)` to compress `.Where(x => x.HasValue).Select(x => x.Value)`

**Comment by vkhorikov** [comment]
Wait, so `Choose` is exactly this method then. We can add an overload without the `selector` argument and probably probably refactor it, to replace `yeild` with the regular LINQ.

We can rename it too (and keep the old method with an `[Obsolete]` mark). What's your opinion on the method name @Razenpok @seangwright ?

* `Choose`,
* `FilterValues`, or
* `MapValues` ?

**Comment by Razenpok** [comment]
At first, I was like

> I think `FilterValues()` and `MapValues(selector)` will make the most sense. Not even sure why `Choose` was picked as a name for such an operation.

But then

> Oh, so there's a `choose` list operator in F# and that's why we have `Choose` here.

This opens up a discussion of the target audience of the library and which side does this library incline to:

- On the one side is F# mimicking: going with `ChooseValues()` and `Choose(selector)`
- On the other side is C# mimicking: going with `WhereHasValues()` and `SelectValues(selector)`
- And there's a middle ground where we are somewhere in-between: `FilterValues()` and `MapValues(selector)`

For me (typical C# developer with almost no F# experience), it's strange to see yet another `Select` synonym which is `Choose` (I already know about `map` from JS). Picking up `WhereHasValues` and `SelectValues` would be the easiest since I'm already familiar with LINQ. `FilterValues` and `MapValues` are also fine I guess.

So, I think the decision should be based on the portrait of the typical user of this library - be it an F# dev or C# dev.

**Comment by seangwright** [comment]
I'm fine with `Choose` and I've used it in F# and with Language-Ext. I know I've seen it in this library before while working on other features, but I guess I never really 'looked' at it.

I imagine I'm not that different from most other developers, in that I do API exploring through intellisense or Go To Definition in my editor.

I think the easiest short-term solution to exposing `Choose()` includes a couple things:
- More complete XML Doc Comments on the methods in the library
- A more comprehensive list of examples in the README showing combinations of operators w/ some explanation and/or a small sample app in the repo

I realize that unit tests can serve a similar role, but it seems to me like the unit tests in this library are more to guarantee there are no regressions in behavior (which could be really bad!) than showing how to use operators.

I can work on a PR that adds more XML doc comments - it's not fun work, but I think it's valuable.

Restructuring/enhancing the README examples is where I think we'll get the most benefit in preventing a 'we already have that operator' situation in the future.

**Comment by vkhorikov** [comment]
I didn't know about `Choose` in F#, but now that I read about it, it makes sense. Just for future reference, here's the difference between `choose` and `filter`:

```ml
List.choose : ('T -> 'U option) -> 'T list -> 'U list
List.filter : ('T -> bool) -> 'T list -> 'T list
```

Let's keep `Choose`. We've already gone the F# way when we separated different `OnSuccess` overloads into `Map` and `Bind`, so I prefer to stick to the F# style for consistency.

@seangwright Regarding the documentation, I've been planning to do it for a long time, but currently my priority is the new course, I hope to work on the documentation once I finish it. Your readme updates look good, feel free to submit a PR, I'll merge them. I also plan to do a separate website with the docs, similar to FluentValidation ( https://fluentvalidation.net/ ), the readme file will be the backbone for that future docs website.
