### ISSUE TITLE
Feature: Maybe.Execute() when there is no value

### ISSUE THREAD

**Issue by seangwright** [vkhorikov/CSharpFunctionalExtensions#328]
`Maybe.Execute()` is effectively shorthand for:

```csharp
Maybe<int> maybe = 10;

maybe.Match(
    number => Console.WriteLine(number),
    () => {});
```

I occasionally come across situations where I want the reverse:

```csharp
Maybe<int> maybe = Maybe<int>.None;

maybe.Match(
    _ => {},
    () => Console.WriteLine("There's nothing here"));
```

Can we add an overload to `Maybe.Execute` that takes an `Action` instead of an `Action<T>` and would be called when there is no value?

```csharp
Maybe<int> maybe = Maybe<int>.None;

maybe.Execute(() => Console.WriteLine("There's nothing here"));
```

**Comment by Razenpok** [comment]
I'm afraid such operator would cause confusion. Maybe `Compensate` would be a better one?

**Comment by vkhorikov** [comment]
I agree regarding confusion, but not sure about `Compensate`. What about `ExecuteNoValue` ?
