### ISSUE TITLE
Maybe.None could be added

### ISSUE THREAD

**Issue by dragan-stepanovic** [vkhorikov/CSharpFunctionalExtensions#34]
I could be wrong, but when I want to instantiate Maybe without value I have to use
`new Maybe<SomeType>()` syntax.
For convenience reason could `Maybe.None` static method be added like in some other Maybe libraries?

**Comment by vkhorikov** [comment]
You can use something like this: `Maybe<SomeType> m = null;`
But I agree, `Maybe.None` would be beneficial as well.
Feel free to submit a PR. Or I will add myself in a little while.

Cheers
Vladimir
