### ISSUE TITLE
Can we connect on skype/discord/zoom?

### ISSUE THREAD

**Issue by ks1990cn** [vkhorikov/CSharpFunctionalExtensions#343]
Hi contributors / @vkhorikov,

Can anyone help us ( we are 2 developers exploring this project) by connecting on skype/discord/zoom?

Just mention at what time zone you are and we can manage a call.

Thanks,
Tanmay Seth
India

**Comment by xavierjohn** [comment]
It will be nice to have a discord channel to have general discussions about this library.
