### ISSUE TITLE
Result with Task Cancellation

### ISSUE THREAD

**Issue by crehmann** [vkhorikov/CSharpFunctionalExtensions#37]
Hi Vladimir,

I really enjoyed your PluralSight course and I really appreciate the thoughts which went into this library.
However, I am not entirely sure how to use the Result struct together with a cancelable task (e.g if I have a method, that returns a Task<Result<SomeClass>>). 
How would you handle the task cancellation? Returning an error result seems to be somehow wrong. I also though about returning a Result<Maybe<SomeClass>>

**Comment by vkhorikov** [comment]
Cancellation looks like a legit outcome of some operation, so I agree Result.Fail would be inappropriate here. I think I would use Task<Result> where overarching task has `Canceled` status, and the inner `Result` is `Ok`. The reasoning being that the method itself did everything well (hence the `Ok` result) and it's the client who requested the method to stop.

**Comment by crehmann** [comment]
I agree, the Task<Result> fits quite nice and seems to be a better choice than Result<Maybe>.
