### ISSUE TITLE
Proposal: Add implicit operator T(Maybe<T> value)

### ISSUE THREAD

**Issue by rutkowskit** [vkhorikov/CSharpFunctionalExtensions#38]
I think it would be nice to be able to implicitly convert `Maybe<T>` to T.
By adding this piece of code to `Maybe<T>`:

```
public static implicit operator T(Maybe<T> maybe)
{
	return maybe._value;
} 

```
it will be possible to do something like this:
```

Maybe<int> maybe = 666;	
int value = maybe;	
int result = value + maybe + value;
```

It will also allow passing directly Maybe<T> to functions with T parameter.

**Comment by vkhorikov** [comment]
An implicit conversion should signalize that the conversion itself is safe, i.e. there can be no exceptions while doing it. Here, a conversion from `Maybe<T>` to `T` can result in an exception if the maybe is empty.

However, an explicit conversion should be good. This way the client knows there's a potential for a problem but if he's willing to take the risk, he can still do that:
```
Maybe<int> maybe = 666;	
int value = (int)maybe;	
int result = value + (int)maybe + value;
```
This would be similar to this code:
```
object o = 2;
int i = (int)o;
```

**Comment by desarrollo03TR** [comment]
If you are doing that, then why not to use the object directly? The idea behind Maybe/Option is avoid nulls and exceptions.

I have my own Option type and I force my self to not use the value directly, I have some extensions methods.

for example:
var opc = "hello".ToOption();

// getting the value or the default value of T is no value:
var x = opc.OrDefault();

// getting the value or another value:
var x = opc.Or("Hi");

If you really want to access to the value, why not add "Value" method as extension?

using Maybe.Nullable:
.
.
var x =opc.GetValue();

**Comment by k3vinco** [comment]
Here are my two cents as an FP amateur:

If you want to use the wrapped type you could do:

1. Use a 'Match' function. This is what you would want use to get the wrapped value out of your Maybe. You should only really use it at the end of your chain.

```
// Implementation

U Match(this Maybe<T> m, Func<T, U> some, Func<U> none)
    => m.HasValue ? some(m.Value) : none()

// Usage

Maybe<Student> student = ...
bool checkForEligibility = person.Match(
    none: () => false,
    some: p => p.Income < 10000); 
```

2. Use a 'Bind' function. This is your bread-and-butter function for chaining monads.

```
// Implementation

Maybe<U> Bind<T, U>(this Maybe<T> m, Func<T, Maybe<U>> f)
    => source.Match(
        none: () => new Maybe<U>(),
        some: f(m.Value)
    );

// Usage

public class Customer
{
    public Maybe<Address> Address { get; set; }
    ...
}

public class Address
{
    public Maybe<PostalCode> PostalCode { get; set; }
    ...
}

Maybe<Order> order = ...
Maybe<GetPostalCode> postalCode = customer
                            .bind(customer => MaybeGetAddress(customer)) // or simply: .bind(MaybeGetAddress)
                            .bind(address => GetPostalCode(address))
```

3. Use a 'Map' function. Map really only define functors not monads (but who cares right), but Maybe is also a functor so we can do this:

```
// Implementation
// Only difference with Bind in terms of code is that the given function returns an unwrapped type, which we wrap ourselves.

Maybe<U> Bind<T, U>(this Maybe<T> m, Func<T, U> f)
    => source.Match(
        none: () => new Maybe<U>(),
        some: f(new Maybe<U>(m.Value))
    );


// Usage
double InnocentSquareRooter(int x) => Math.Sqrt(x); // This function has no idea about Maybe, IEnumerable etc.

Maybe<string> userInput = ...
Maybe<double> squareRootInput = userInput.Map(InnocentSquareRooter);
```

So in your case you would probably want to do this:

```
Maybe<int> maybe = 666;

int result = maybe.Match(
                    None: () => 0
                    Some: value =>
                            {
                                int value = maybe;	
                                return value + maybe + value;
                            });

// OR

int Sum(int left, int right) => left + right;

Maybe<int> maybe = 666;

Maybe<int> value = maybe;	
int result = value
                .Map(n => Sum(n, maybe))
                .Map(n => Sum(n, value));

int result = maybe.Match(
    None: () => 0
    Some: value => value);
```
