### ISSUE TITLE
[Question] `Entity.IsTransient` needed with EF Core?

### ISSUE THREAD

**Issue by lonix1** [vkhorikov/CSharpFunctionalExtensions#391]
The [entity base class](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/a3c3059f1d7146ed389ad890ef97bc8448051f43/CSharpFunctionalExtensions/Entity/Entity.cs?rgh-link-date=2022-02-14T11%3A53%3A04Z#L33) has `IsTransient`, which is used in the equality check.

Does anyone know its purpose... is it for NHibernate?

If I'm using EF Core, can I assume that it's not needed at all?

**Comment by vkhorikov** [comment]
It's relevant for both EF and NH. Transient means that the object has not yet been persisted and so you can't check equality properly because of lack of id, hence 2 transient objects are deemed not equal.

**Comment by lonix1** [comment]
Understood, and thanks!
