### ISSUE TITLE
Initializing new Maybe object

### ISSUE THREAD

**Issue by gregberns** [vkhorikov/CSharpFunctionalExtensions#4]
First, this is an awesome library!! I have been using it for several days and I love the control flow.

One change I'd like to suggest is to the Maybe module. It works great if you want to expose a Maybe<object> as a property. But I'd like to be able to create a new Maybe object and pass it on.

For example, an error occurs and I just want to ignore it and return a Maybe. Currently, it seems like you have to create a new variable and return it. This is a little ugly in a lambda.

```
.OnBoth(result =>
 {
       Maybe<CachedVehicle> ret = result.IsSuccess ? result.Value : null;
       return Result.Ok(ret);
})
```

I'd prefer to do something like this:
```
.OnBoth(result => Result.Ok(Maybe<CachedVehicle>(result.IsSuccess ? result.Value : null))
```
Does that make sense? Did I miss something and maybe this is already possible?

**Comment by vkhorikov** [comment]
Thanks! Glad you found the library helpful.

Actually, you can do this sort of operation using explicit conversion. Try this:

```
.OnBoth(result => Result.Ok((Maybe<CachedVehicle>)(result.IsSuccess ? result.Value : null)))
```

**Comment by gregberns** [comment]
Ah! Beautiful. Thought I tried that but didn't put parens around both. Thanks again for the great library.
