### ISSUE TITLE
Cannot Access Maybe<T>.None on .NET 4.6.2

### ISSUE THREAD

**Issue by valainisgt** [vkhorikov/CSharpFunctionalExtensions#40]
Hello,

I am using your library within a .NET 4.6.2 project and cannot access the Maybe<T>.None static property.

The following does not compile (error is: 'Maybe<MyClass>' does not contain a definition for 'None'):
`Maybe<MyClass> none = Maybe<MyClass>.None;`

But this does:
`Maybe<MyClass> none = null;`

What's going on here?

Thanks,
Greg Valainis

**Comment by vkhorikov** [comment]
Hi Greg, thanks for the ticket. I need to push a new version of the library to NuGet. Will do that shortly.

**Comment by vkhorikov** [comment]
The new version is out, please try it out. Thanks.

**Comment by valainisgt** [comment]
Did not mean to re-open.  Was unaware that value types were not supported by Maybe<T>
