### ISSUE TITLE
Request: Remove obsolete methods

### ISSUE THREAD

**Issue by Paul-Williams** [vkhorikov/CSharpFunctionalExtensions#417]
Would it be possible to draw a line and remove the multitude of obsolete methods from the various `Result` classes? 
They seem to have been building up over time, due to ad-hoc design, but surely they have to go, sometime?
I would be happy to do this myself, but would not want to step on anyones toes...

**Comment by Paul-Williams** [comment]
Or even, perhaps, annotate them with `[EditorBrowsable(EditorBrowsableState.Never)]` to prevent them appearing in intellisense.

**Comment by vkhorikov** [comment]
I like the latter option better. Keep them in the code (for now at least) but don't show in IntelliSense's code completion. A PR is welcome.

**Comment by vkhorikov** [comment]
Thank you. Please go ahead with `Maybe` (and any other classes you may find) as well, for consistency sake. I'll publish a new lib version after that.

**Comment by Paul-Williams** [comment]
As requested, have applied EditorBrowsableAttribute obsolete methods  in `MaybeExtensions` class.
PR: #419

**Comment by vkhorikov** [comment]
Thank you. Will be published with v2.29.4 shortly.

**Comment by Paul-Williams** [comment]
My pleasure. Thank you for the excellent library and accompanying Plurasight course! Headed my down the path of functional-like programming ;)
