### ISSUE TITLE
Problem after updating to nuget package version 2.33

### ISSUE THREAD

**Issue by rutkowskit** [vkhorikov/CSharpFunctionalExtensions#436]
Hello,
I think there is something wrong with nuget package 2.33. 
After upgrade, my build is breaking on "TapIf" methods.

Was it deleted on purpose?

Downgrading to version 2.32 fixed the problems with compilation.

**Comment by vkhorikov** [comment]
Let me check. Could you please post the code that no longer compiles?

**Comment by rutkowskit** [comment]
I have errors for these missing extensions:

```csharp
public static Task<Result> TapIf(this Result result, bool condition, Func<Task> action);
public static Task<Result<T>> TapIf<T>(this Task<Result<T>> resultTask, bool condition, Action<T> action);    
public static Task<Result<T>> TapIf<T>(this Task<Result<T>> resultTask, Func<T, bool> condition, Action<T> action);
public static Task<Result<T>> TapIf<T>(this Result<T> result, Func<T, bool> condition, Func<T, Task> action);
public static Result<T> TapIf<T>(this Result<T> result, bool condition, Action<T> action);
public static Result<T> TapIf<T>(this Result<T> result, Func<T, bool> condition, Action<T> action);
```
I checked in the "Main Branch" code, and it seems that all the "TapIf" was removed in this version (except the obsolete ones), so i guess the problem applies to all "TapIf" extensions.

**Comment by vkhorikov** [comment]
Returned those methods back, a new version 2.33.1 will be published in ~5 minutes, could you please check?

**Comment by rutkowskit** [comment]
Updated to version 2.33.1. 
No error during compilation.
Thank You :)
