### ISSUE TITLE
Bind method documentation suggested returns 'Maybe' -- However, a 'Result' is returned

### ISSUE THREAD

**Issue by jeffward01** [vkhorikov/CSharpFunctionalExtensions#468]
I noticed that in the `Bind` method it says [this](https://github.com/vkhorikov/CSharpFunctionalExtensions#bind):
> Use case: Transforming from one Maybe into another Maybe (like Maybe.Map but it transforms the Maybe instead of the inner value)
> Note: the delegate (ex MakeAppleSauce) passed to Maybe.Bind() is only executed if the Maybe has an inner value

Now I have (2) examples:

This returns a `Result<TEntity, Error>` type:
```csharp

var result =   this.Queryable.AsMaybe()
            .ToResult(DomainErrors.NullOrEmpty.DbSetQueryable)
            .Tap(_ => _.Apply(specification))
            .Tap(_ => _.WithId(entity.Id))
            .Bind(
                q => q.FirstMaybe()
                    .ToResult(DomainErrors.NotFound.BySpecificationAndKey))
            .Ensure(_ => _.IsActive(), DomainErrors.EntityState.EntityNotActive)
            .Tap(this.AttachEntity)
            .Tap(_ => _.MarkDeactivate());
```

^^ The above is expected to return result because the last method is `Tap()`
This is the description for `Tap()`

> Executes the given action if the calling result is a success. Returns the calling result.

Second example:

This also returns a `Result<TEntity, Error>` type. 
```csharp

var thisIsAlsoResult = this.Queryable.AsMaybe()
            .ToResult(DomainErrors.NullOrEmpty.DbSetQueryable)
            .Ensure(_ => id.IsNotEmpty(), DomainErrors.NullOrEmpty.ProvidedKey)
            .Tap(_ => _.Apply(whereExpression))
            .Tap(_ => _.WithId(id))
            .Bind(
                _ => _.FirstOrDefault()
                    .AsMaybe()
                    .ToResult(DomainErrors.NotFound.ByWhereExpressionAndKey));
```

Based on the documentation in the `README.md` , I would expect the second example to return a `Maybe<TEntity>` instead.  

----

Am I not understanding something?  

In this case is my understanding incorrect, or the `xml` comment for `Bind` incorrect, or something else?

Thanks!

_Originally posted by @jeffward01 in https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/467#issuecomment-1328848541_

**Comment by vkhorikov** [comment]
`Bind` is for all monads, be it `Maybe` or `Result`. Check out this article: https://fsharpforfunandprofit.com/posts/elevated-world-2/

**Comment by jeffward01** [comment]
Thank you!!

At some point in the future I plan to update the documentation, or perhaps add some tutorials for new functional programmers like myself.

Thank you!
