### ISSUE TITLE
Missing Match for UnitResult

### ISSUE THREAD

**Issue by thomaseyde** [vkhorikov/CSharpFunctionalExtensions#483]
I miss the following `Match` method for `UnitResult`:

```csharp
static class MatchUnitResult
{
    public static R Match<E, R>(this UnitResult<E> result, Func<R> success, Func<E, R> failure) =>
        result.IsSuccess
            ? success()
            : failure(result.Error);
}
```

**Comment by vkhorikov** [comment]
Thanks for reporting this. Feel free to submit a PR as well.

**Comment by bothzoli** [comment]
This method is already implemented, so I believe this issue could be closed.

https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/7eb1ae86570ebf6057eb446fdf1cd3f6cc1d0be8/CSharpFunctionalExtensions/Result/Methods/Extensions/Match.cs#L43-L48
