### ISSUE TITLE
Support for .NET core required

### ISSUE THREAD

**Issue by alex-erygin** [vkhorikov/CSharpFunctionalExtensions#5]
Hi, can you add support for .NET core?

**Comment by vkhorikov** [comment]
That would indeed be great. Not sure about timeline, but I'll try to do that.

**Comment by alex-erygin** [comment]
Now it forks perfectly for .NET and Universal Windows Platform. Xamarin and .NET Core not tested yet.

**Comment by vkhorikov** [comment]
Should be working in .NET Core now.
