### ISSUE TITLE
Adding an implicit operator for T to the Result<T> class to get the value?

### ISSUE THREAD

**Issue by leblancdavid** [vkhorikov/CSharpFunctionalExtensions#51]
I was wondering if this would be a good addition to the `Result<T>` class:
```csharp
public static implicit operator T(Result<T> result) { return result.Value; }
```
The benefits of this implicit operator removes the need for doing `result.Value` in many places. For example:
```csharp
public TestClass()
{
            var result = Result.Ok(new Foo());
            //instead of: Foo foo = result.Value
            Foo foo = result;

            //instead of: MethodThatTakesFoo(result.Value)
            MethodThatTakesFoo(result);
}
public void MethodThatTakesFoo(Foo value)  { }
```

The other benefit is you could rename your `var` names:
```csharp
//instead of: var userOrError = ...
var user = userRepository.GetUser(id);
if(user.IsFailure) { }
//Do stuff to the user
//instead of: userRepository.UpdateUser(userOrError.Value);
userRepository.UpdateUser(user);
```

I've noticed I find myself passing the result into other methods and forgetting the `.Value` (which obviously causes a compile error). Also, I'm not a big fan of the name "Value", as it is a little too generic and adds a bit of clutter in my opinion. I'm curious about your thoughts on this change. What would be the potential issues/drawback with doing this approach?

Thanks

**Comment by vkhorikov** [comment]
An implicit conversion should signalize that the conversion itself is safe, i.e. there can be no exceptions while doing it. Here, a conversion from `Result<T>` to `T` can throw an exception if the result was unsuccessful.

In FP, the usual way of preventing all those `.Value` calls is using higher order functions, i.e. the extension methods like `OnSuccess`, `OnFailure`, etc.

This might not work well in complex scenarios, though, so we are pretty much stuck with `.Value`

**Comment by leblancdavid** [comment]
Good points, I didn't think about `OnSuccess` or `OnFailure`. 

However, how would the conversion from `Result<T>` to `T` fail? If the conversion returns `.Value`, you would get a null reference on result fails whether you are using the implicit conversion, or calling `.Value` if you fail to check the `IsSuccess` or `IsFailure` flags.

**Comment by vkhorikov** [comment]
The current implementation throws on `.Value` if the result is not a success ( https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/b26c636f04537e2e63ab669eaf035178c133e67b/CSharpFunctionalExtensions/Result.cs ). And I believe it should stay this way. Calling `.Value` is valid only if there's an actual result out there, otherwise it would introduce hard-to-catch issues like null reference exceptions down the road.

**Comment by leblancdavid** [comment]
I can see how throwing an exception on the implicit call might make it hard for people to catch. Thank you for the explanation. Keep up the great work!
