### ISSUE TITLE
Proposal for a TapIf overload

### ISSUE THREAD

**Issue by fliebrecht** [vkhorikov/CSharpFunctionalExtensions#515]
I think the overload of TapIf with the signature (**this Task<Result> resultTask, Func<bool> predicate, Action action**) is missing (hopefully my implementation is correct):

        public static async Task<Result> TapIf(this Task<Result> resultTask, Func<bool> predicate, Action action)
        {
            Result result = await resultTask.DefaultAwait();

            if (result.IsSuccess && predicate())
                return result.Tap(action);
            else
                return result;
        }

**Comment by vkhorikov** [comment]
Looks good to me, feel free to submit a PR.
