### ISSUE TITLE
default ConfigureAwait(false) is causing to lose thread culture

### ISSUE THREAD

**Issue by vukasinspasic** [vkhorikov/CSharpFunctionalExtensions#53]
I have a heavy usage of your functional library, it is doing a great job as part of API project. The problem I noticed is that after calling OnSuccess or ToResult on async methods current thread culture is lost because you are using ConfigureAwait(false) as default which doesn't return to thread caller, but to first available thread. I know OnSuccess and ToResult have parameter bool continueOnCapturedContext = false that I can set to true, but I wouldn't want to do this on every place in code. So my question actually is, why do you have ConfigureAwait(false) in your library when .NET is continuing on captured context ( ConfigureAwait(true) ) by default? And is it possible that you set continueOnCapturedContext  to have default value = true?

**Comment by vkhorikov** [comment]
The primary reason was to help avoid potential dead locks where people are using methods from the library in a blocking context, such as `DoSomething().Result` where `DoSomething` returns a `Task`.

I'm actually OK with changing this behavior as people shouldn't be using `.Result` anyway and it's quite easy to avoid using it in scenarios with API.

If you could do a PR, I'd release a new version of the lib.

**Comment by vukasinspasic** [comment]
Thank you very much for fast answer! I will try to make PR soon

**Comment by vkhorikov** [comment]
Available in 1.10.0

**Comment by vukasinspasic** [comment]
Thank you @vkhorikov and @robosek
