### ISSUE TITLE
Add IError<string> to the Result struct

### ISSUE THREAD

**Issue by nicksoethof** [vkhorikov/CSharpFunctionalExtensions#546]
Why is the Result.cs struct not decorated with the `IError<string>` interface? The `Result<T>` struct does have the `IError<string>` interface decorated.

Both the `Result` and the `Result<T>` structs have the `string Error` property.

We could just add the interface without any issue, like below:
```csharp
[Serializable]
public readonly partial struct Result : IResult, ISerializable, IError<string>
{
```

**Comment by vkhorikov** [comment]
Yeah, that was an oversight on my part. Feel free to submit a PR with a fix.

**Comment by bothzoli** [comment]
Feel free to review the PR.
`Result<T>` didn't need this interface as it already implements it via the following:
- `Result<T> : IResult<T>`
- `IResult<out T> : IResult<T, string>`
- `IResult<out T, out E> : IValue<T>, IUnitResult<E>` (`<E>` is string at this point)
- `IUnitResult<out E> : IResult, IError<E>` (`<E>` is string at this point)

**Comment by vkhorikov** [comment]
Merged it, thank you.
