### ISSUE TITLE
[Suggestion] Add async & func overloads for `Maybe.From`

### ISSUE THREAD

**Issue by DerStimmler** [vkhorikov/CSharpFunctionalExtensions#568]
I think it would be nice to have `async` overloads for `Maybe.From` to create a new `Maybe` object from an async value.

```csharp
await Maybe.From(_service.FindAsync())
```

Just as with `Result.Of` we could also add `Func` overloads to add some flexibility.

```csharp
Maybe.From(() => _service.Find())
```

```csharp
await Maybe.From(() => _service.FindAsync())
```

**Comment by vkhorikov** [comment]
Yep, good idea.
