### ISSUE TITLE
v3.0.0 GetValueOrDefault() returns nullable when default value is not nullable

### ISSUE THREAD

**Issue by seangwright** [vkhorikov/CSharpFunctionalExtensions#570]
## Environment

- .NET 8, C# 12, VS Code, C# DevKit
- I have NRT enabled and warnings as errors.
- Here are the types of the properties in the following example

## Types

- `WebPageMetaTitle` - `string`
- `BlogPostPageBlogPostContent` - `IEnumerable<T>`
- `ListableItemTitle` - `string`

Here's my custom extension

```csharp
public static Maybe<string> MapNullOrWhiteSpaceAsNone(this Maybe<string> value) =>
        value.Bind(v => string.IsNullOrWhiteSpace(v) ? Maybe.None : Maybe.From(v));
```

## Example

Now I'm seeing an error with `.GetValueOrDefault()` when I provide it a non-null default.

```csharp
string metaTitle = Maybe
            .From(WebPageMetaTitle)
            .MapNullOrWhiteSpaceAsNone()
            .IfNoValue(BlogPostPageBlogPostContent
                .TryFirst()
                .Bind(c => Maybe.From(c.ListableItemTitle).MapNullOrWhiteSpaceAsNone()))
            .GetValueOrDefault(""); // ERROR: Converting null literal or possible null value to non-nullable type.
```

## Workarounds

It is unfortunate that I now need to do one of the following

1. `.GetValueOrDefault("") ?? "";`
2. Create my own extension `.GetValueOrDefaultNotNull("");` that is typed as `public T GetValueOrDefaultNotNull(T defaultValue = default(T))`
3.  `.GetValueOrDefault("")!;`
4. `.TryGetValue(out string? val) ? val : "";`
5. `.Match(v => v, _ => "");` - for some reason the overload resolution no longer works here and I get the compilation error `Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement`

**Comment by vkhorikov** [comment]
Could you try v3.1.0 and let me know if this is fixed? Made some adjustments to that method.

**Comment by seangwright** [comment]
v3.1.0 resolved the issue! Thanks
