### ISSUE TITLE
Proposal: Ensure `null` with `Maybe`

### ISSUE THREAD

**Issue by DerStimmler** [vkhorikov/CSharpFunctionalExtensions#571]
Currently, the `ToResult` method on `Maybe` returns a success result if the `Maybe` has a value, and a failure result if there is no value.

But what if it should be the other way around?

---

Lets say I want to create a report, but only if no report already exists.

Right now I would probably do something like this:

```csharp
await Result
      .Success()
      .Map(() => service.FindAsync(id)) //returns Report?
      .Ensure(report => report is null, "There is already a report available.")
      .Tap(_ => service.CreateReport())
      ...
```

But this comes with some overhead because I have to start the chain with an empty success result to then map the nullable value and ensure its `null` using the `Ensure` method.

I think it would be more appropriate and compact to use `Maybe` and its `ToResult` method since I'm dealing with a nullable.

But to keep the chain running if the `Maybe` has no value, I basically need an inverted `ToResult` method that returns a success result if there is no value. E.g:

```csharp
await Maybe
      .From(service.FindAsync(id))
      .ToInvertedResult("There is already a report available.") //returns success result if Maybe has no value, otherwise returns failure result with error message
      .Tap(() => service.CreateReport())
      ...
```

---

What do you think about this addition?

`ToInvertedResult` is just an example name because I can't think of anything better. 😄

**Comment by vkhorikov** [comment]
Yeah, sounds useful enough. Feel free to submit a PR. Can't think of a better name than `ToInvertedResult` either :)

**Comment by bothzoli** [comment]
Hey @DerStimmler, @vkhorikov,
I'm happy to give this one a shot in the coming days.

**Comment by bothzoli** [comment]
If I'm correct with my thinking, this will return a vanilla `Result` for `Maybe<T>` and a `UnitResult<E>` when using a custom failure.
Because I cannot populate a `T` from a failed `Maybe<T>` for it to be `Result<T>` (or populate a `T` for a `Result<T, E>` from a `Maybe<T,E>`).

But I believe it would probably make sense to add overrides which could do just that, like:
`Result<T> ToInvertedResult<T>(in this Maybe<T> maybe, string errorMessage, Func<T> compensate)`
or 
`Result<T> ToInvertedResult<T>(in this Maybe<T> maybe, string errorMessage, Func<string, T> compensate)`

Any thoughts?

**Comment by DerStimmler** [comment]
Hi @bothzoli,
thanks for your help.

I think you are right with `Result` and `UnitResult<E>` as return types.

I don't think we need the compensate func since there is already a `Compensate` operation.
Then it would look like this:

```csharp
Maybe.From("Foo")
  .ToInvertedResult("Bar")
  .Compensate(error => ...)
```

Since we can create `Task<Maybe<T>>` from async values the `ToInvertedResult` methods need async variants.

```csharp
await Maybe.From(Task.FromResult("Foo"))
  .ToInvertedResult("Bar");
```

[Here](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/Maybe/Extensions/ToResult.Task.cs) are some async examples for the normal `ToResult` method for reference.

**Comment by bothzoli** [comment]
Hey @DerStimmler,
Thanks for the quick feedback. Yeap I'll make sure that the async use-case is also covered, I just wanted to make sure I understood the issue correctly (hence the PR still in draft).
I'll try to tie up all the loose ends in the coming days and issue the PR.
Cheers

**Comment by bothzoli** [comment]
@DerStimmler I've finalised the PR, feel free to review.

**Comment by DerStimmler** [comment]
Great, I'll have a look at it.
