### ISSUE TITLE
CSharpFunctionalExtensions.dll does not represent a strongly named assembly

### ISSUE THREAD

**Issue by andreaskasc** [vkhorikov/CSharpFunctionalExtensions#573]
Although I have seen that the issue for strong named assembly #27 is closed with PR #543 and this was also mentioned in [2.45.1 release notes](https://github.com/vkhorikov/CSharpFunctionalExtensions/releases/tag/v2.42.1), when I installed the package I still got a warning while building my project: 
_CSC : warning CS8002: Referenced assembly 'CSharpFunctionalExtensions, Version=2.42.5.0, Culture=neutral, PublicKeyToke
n=null' does not have a strong name._ 

I then tried to manually verify if the assembly is strong named  and I see that it is not. I used sn.exe tool 

1. **Open Developer Command Prompt**: Open the Developer Command Prompt for Visual Studio.
2. **Run the `sn.exe` Command**: Use the following command to check the strong name status of the DLL:
```sh
sn -vf CSharpFunctionalExtensions.dll
```
Below is full example and the result I got:
```sh
PS <LocalPath>\csharpfunctionalextensions.2.42.5\lib\netstandard2.0> sn -vf CSharpFunctionalExtensions.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

CSharpFunctionalExtensions.dll does not represent a strongly named assembly

```
I have tried all versions and all .net version (not only _netstandard2.0_ folder) that are supposed to have a strong named assembly, i.e. 2.45.1+ with the same result.

Am I missing something?

@bothzoli

**Comment by bothzoli** [comment]
Hey mate,

The strong named assembly is released as a separate nuget package.
See this link:
https://www.nuget.org/packages/CSharpFunctionalExtensions.StrongName

**Comment by andreaskasc** [comment]
My bad, I missed that this was a new NuGet package.

**Comment by andreaskasc** [comment]
My bad, I missed that this was a new NuGet package. Thanks @bothzoli
