### ISSUE TITLE
Result with error type

### ISSUE THREAD

**Issue by alexmaie** [vkhorikov/CSharpFunctionalExtensions#58]
Hey guys,
First of all a very usefull library :) .

1. When using error types (Result<int, SomeType> ) in an Onsuccess method that is calling an async method, the resulting Result is wrapped in another Result

Example
```
Task<Result<int,ErrorType>> GetSomething(){ ... }

var theResult= await Result.Ok().OnSuccess( () => GetSomething());
```                         
theResult will be of type Result<Result<int,ErrorType>>

If the example is not clear, please let me know and I will create a test project

I suppose that the methods in AsyncResultExtensionsRightOperand need to be extended

2. 
It would be nice to be able to use an error object without the need to also have a return type for value. Maybe an interface needs to be introduced

**Comment by igor-toporet** [comment]
Yeah, we started using the Result and Railway-oriented approaches extensively at my company and for some algorithms we needed to distinguish between possible short-circuit paths. I wasn't sold to the idea of having one uber-enumeration for all errors. 

This motivated me to play around trying introduce `Result<TValue,TError>` that'd be relatively easy to use in various real-life scenarios. Feel free to check out following repository https://bitbucket.org/igor-toporet/result_experiment/ and let me know if it works for you.

**Comment by bothzoli** [comment]
I believe this is now covered by the [`Result<T, E>`](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/Result/ResultTE.cs).
See also #33 which I think is analogous to this one.

**Comment by alexmaie** [comment]
yeah, we can close this thread :D

**Comment by vkhorikov** [comment]
A 6 year thread! 😮
