### ISSUE TITLE
Tests failures are ignored in CI pipeline

### ISSUE THREAD

**Issue by marcinjahn** [vkhorikov/CSharpFunctionalExtensions#580]
At the moment, tests are not even executed due to .NET version mismatch. Tests project targets .NET 6, while only 8.x SDK is available.

> Testhost process for source(s) '/app/CSharpFunctionalExtensions.Tests/bin/Release/net6.0/CSharpFunctionalExtensions.Tests.dll' exited with error: You must install or update .NET to run this application.

Any PR to this repository has misleading build result - it's green even though tests did not run at all.

**Comment by vkhorikov** [comment]
Ooff. This went unnoticed after removing the old .net references

**Comment by bothzoli** [comment]
Oops, that's my mistake, I honestly didn't notice that the tests were failing.
I'll start working on a fix 😉
Sorry about that 😇

**Comment by bothzoli** [comment]
@vkhorikov please see the fix for this in #586.
