### ISSUE TITLE
Remove obsolete BinaryFormatter from tests

### ISSUE THREAD

**Issue by bothzoli** [vkhorikov/CSharpFunctionalExtensions#587]
Since .NET 7 `Serialize` and `Deserialize` on `BinaryFormatter` produce compile errors (see [here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/7.0/binaryformatter-apis-produce-errors)).

These methods are currently used in the test classes `CSharpFunctionalExtensions.Tests/MaybeTests/DeserializationTests.cs` and `CSharpFunctionalExtensions.Tests/ResultTests/DeserializationTests.cs`.

With #586 this error is switched off to allow tests to succeed, but the corresponding tests should be removed or updated to use a different serializer.

The switching off happens in `CSharpFunctionalExtensions.Tests/CSharpFunctionalExtensions.Tests.csproj` with `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` added.

**Comment by bothzoli** [comment]
As also mentioned in #584 since `Result` (and also `Maybe`) types are not serializable, I wonder if it makes sense to keep these tests?

**Comment by vkhorikov** [comment]
We can remove them. We shouldn't have made `Result` serializable either btw.

**Comment by bothzoli** [comment]
Thanks, I'm happy to create a PR removing the tests.
Should I also remove the `ISerializable` interface from `Result` or would you prefer to do that for a major release?

**Comment by vkhorikov** [comment]
Please do. Let's keep `ISerializable` for now as it's going to be a breaking change.

**Comment by bothzoli** [comment]
@vkhorikov PR #592 is ready for review.
