### ISSUE TITLE
ResultExtensions, why Ensure creates new instance of Result?

### ISSUE THREAD

**Issue by Szychulski** [vkhorikov/CSharpFunctionalExtensions#62]
Hi, is there a reason that Ensure method creates a new instances of result? 
We can just return current result object if current result.IsFailure.

` public static Result<T> Ensure<T>(this Result<T> result, Func<T, bool> predicate, string errorMessage)
        {
            if (result.IsFailure)
                return Result.Fail<T>(result.Error);

            if (!predicate(result.Value))
                return Result.Fail<T>(errorMessage);

            return Result.Ok(result.Value);
        }`

**Comment by vkhorikov** [comment]
You are right, no need in instantiating a new one here

**Comment by ahryshchanka** [comment]
It issue fixed in https://github.com/vkhorikov/CSharpFunctionalExtensions/pull/81
