### ISSUE TITLE
Make error message separator , configureable

### ISSUE THREAD

**Issue by altmann** [vkhorikov/CSharpFunctionalExtensions#66]
We use this library in our project but we have one suggestion. It would be cool if it is able to configure the error message separator which is now the constant ", " on one central point. 

For example:

    Result.SetupErrorMessageSeparator("$$");

I know, it is able to pass the error message separator on method level like 

    Result.Combine("$$", r1, r2);

But this is not a solution for us because then we have to pass the separator on each usage of combine. 

Do you see a opportunity to implement this?

**Comment by vkhorikov** [comment]
Don't see why not. You can create a PR and I'll publish a new version. Alternatively, I can do that myself but but that can take awhile.

**Comment by altmann** [comment]
Ok, that seems fair. We will send you an PR in the next weeks/months.

**Comment by altmann** [comment]
@vkhorikov Can you please publish a new version to Nuget. We need this new feature in the next days. 

Thank you...

**Comment by vkhorikov** [comment]
Published: 1.17.0
