### ISSUE TITLE
ResultExtensions: OnFailure

### ISSUE THREAD

**Issue by peteski22** [vkhorikov/CSharpFunctionalExtensions#7]
Hi, apologies if I've gotten this completely wrong.. I was reading your article: http://enterprisecraftsmanship.com/2015/03/20/functional-c-handling-failures-input-errors/

It discusses the use of the OnFailure extension method for Result, but looking the Nuget package doesn't appear to have this method, the commits on GitHub also don't appear to have the method, am I missing something?

Thanks
Peter

**Comment by vkhorikov** [comment]
You are absolutely right, I haven't added them to the library yet. I'll add them on this week-end, and will release a new version.

Thanks for pointing this out!

Vlad

**Comment by peteski22** [comment]
Thanks so much, also for the blog post, PluralSight course and creating the
Nuget package!

:)

**Comment by vkhorikov** [comment]
Just pushed a new version - 1.5.0 - of the package. Let me know if you have any issues with the OnFailure extension method.

**Comment by peteski22** [comment]
Hey Vlad, should there be additional overloads of the for OnFailure method (similar to the OnSuccess ones)? To allow you to pass deal with the result object.

i.e.

myResult.OnFailure((Result<T> r) => DoSomething(r.Error));

**Comment by vkhorikov** [comment]
Was out for several days, haven't had a chance to merge the PR.

It looked good, however. Did you find some issues with it? Or why did you close it?

**Comment by peteski22** [comment]
Hey Vlad,

Apologies, I think I had missed quite a lot out as I didn't see the
Left/Right operand stuff only the ResultExtensions.cs main class :( so I
pulled the pull request.

I've been having quite a lot of trouble using the extensions, I think it's
more user error due to coming from a more imperative style of programming.

I'd be happy to chat about it with you if you'd like?

Thanks
Peter

**Comment by vkhorikov** [comment]
Hi Peter,

Don't worry about the Left/Right operands, they're just overloads for various async combinations. You can add the overloads you care about and I'll go through the code base and fill in corresponding overloads for them.

Regarding the trouble using the extensions, could you elaborate on what they are? Would be glad to help with that.

Cheers
Vlad

**Comment by vkhorikov** [comment]
I've added the overload for OnFailure you were trying to add recently ([lines](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ResultExtensions.cs#L151-L158)). It went live with the version 1.6.1. Let me know if you have any questions, I'd be glad to help with them.
