### ISSUE TITLE
Result Try method

### ISSUE THREAD

**Issue by kitsu** [vkhorikov/CSharpFunctionalExtensions#70]
I'm using your Result object with a third-party library that communicates using exceptions. I'd like to _lift_ the exceptions into a failed Result. My current code just returns a different Result from each branch of the try-catch.

I'm thinking something like:
``` CSharp
Result.Try(() => library.ThingThatMightFail(),
           (ex) => "Some error message, possibly branching on exception type...");

// Where
Try<Result<T>>(Func<T> attempt, Func<Exception,string> failure)
```

Handling specific exceptions can be done with `ex is SomeException`, and truly unexpected exceptions can be rethrown.

This would just be a convenience method, but often the reason I'm using a Result is to hide library exceptions behind more user friendly error messages.

**Comment by freakingawesome** [comment]
I cobbled together a quick implementation of what this could look like.

```c#
// static method on Result
public static Result<T> Try<T>(Func<T> f, Func<Exception, Maybe<string>> handler)
{
    try
    {
        return Result.Ok(f());
    }
    catch (Exception x)
    {
        var handled = handler(x);
        if (handled.HasValue)
        {
            return Result.Fail<T>(handled.Value);
        }

        throw;
    }
}

// an extension for chaining
public static Result<T> OnSuccessTry<T>(this Result<T> self, Func<T> f, Func<Exception, Maybe<string>> handler) =>
    self.IsFailure ? self : Try(f, handler);
```

It's important to rethrow via `throw;` rather than `throw x;` because the `throw;` variation retains the original call stack, whereas `throw x;` creates a new call stack.

There could be lots of variations on this theme - async, handlers that return `Result`, etc.

**Comment by ahryshchanka** [comment]
@vkhorikov is it make sense to implement this extension methods?

**Comment by ahryshchanka** [comment]
@vkhorikov looks like this issue resolved and can be closed
