### ISSUE TITLE
EqualityComparer for Maybe<Dynamic> returns not equals for Maybe<>.None.

### ISSUE THREAD

**Issue by kostekk88** [vkhorikov/CSharpFunctionalExtensions#77]
Hi, 
I came across this issue while investigating a problem in other open project (NSubstitute). After some ffiddling I think I managed to trace it to the implementation of EqualityComparer for Maybe<>. 

They say code is worth 1000 words, so here is the sample : 

        [Test]
        public void Bug_MaybeDynamicNone()
        {
            var compareUsingMaybeDynamic = EqualityComparer<Maybe<dynamic>>.Default.Equals(Maybe<dynamic>.None, Maybe<dynamic>.None);
            
            var compareObjectNotDynamic = EqualityComparer<object>.Default.Equals(Maybe<int>.None, Maybe<int>.None);

            var compareDynamicInt = EqualityComparer<object>.Default.Equals((dynamic)1, (dynamic)1);

            //NSubstitute is using object as generic type which doesnt work for Maybe<dynamic>
            var compareUsingMaybeObject = EqualityComparer<object>.Default.Equals(Maybe<dynamic>.None, Maybe<dynamic>.None);

            Assert.IsTrue(compareUsingMaybeDynamic);
            Assert.IsTrue(compareObjectNotDynamic);
            Assert.IsTrue(compareDynamicInt);
            Assert.IsTrue(compareUsingMaybeObject); // Only comparission of Maybe<dynamic>.None using object comparer fails.
        }

        [Test]
        public void Bug_DefaultInstance()
        {
            var compareMaybeIntUsingObject = EqualityComparer<object>.Default.Equals(Activator.CreateInstance(typeof(Maybe<int>)), Activator.CreateInstance(typeof(Maybe<int>)));

            var compareUsingMaybeDynamic = EqualityComparer<Maybe<dynamic>>.Default.Equals(Activator.CreateInstance(typeof(Maybe<dynamic>)), Activator.CreateInstance(typeof(Maybe<dynamic>)));

            //NSubstitute is using object as generic type which doesnt work for Maybe<dynamic>
            var compareMaybeDynamicUsingObject = EqualityComparer<object>.Default.Equals(Activator.CreateInstance(typeof(Maybe<dynamic>)), Activator.CreateInstance(typeof(Maybe<dynamic>)));

            Assert.IsTrue(compareMaybeIntUsingObject);
            Assert.IsTrue(compareUsingMaybeDynamic); // Surprisingly this one fails for Default instance but not for Maybe<>.None
            Assert.IsTrue(compareMaybeDynamicUsingObject); //Here is the same problem as with Maybe<dynamic>.None in the test above 
        }

I hope this will be enough to reproduce it. In case you need any more information let me know. 

Regards
K. 

Edit: 
I found even simpler repro 

```
var equals = Maybe<dynamic>.None == (dynamic)Maybe<dynamic>.None;
Assert.True(equals);
```

also found where the problem is  Line 71 in Maybe<>
```
if (obj is T)
{
    obj = new Maybe<T>((T)obj);
}
```
This check will pass for dynamic and will create new object with value in it which will fail down the line since current object HasNoValue while the newly created one Has.

Edit 2: 
Actually 
`Maybe<dynamic>.None == (dynamic)Maybe<dynamic>.None;`
Is a problem with Implicit conversion while my problems were in Equals. 
Changing line 71 to 
`  if (obj is T && !(obj is Maybe<T>))`
fixes my problem but doesnt fix implicit conversion bug. I tried to find something to make also this one go away, but only thing I found was an infinite implicit conversion :)

Thats all I've got :) Hope this helps. 

K.

**Comment by kostekk88** [comment]
Ups, didnt mean to close it :)

**Comment by vkhorikov** [comment]
Pushed a new version to nuget, let me know if it works for you.

**Comment by kostekk88** [comment]
This is a hell of response time! It works like a charm. Thank you.
