### ISSUE TITLE
Add extension method Combine for IEnumerable<Result<T>> / IEnumerable<Result>

### ISSUE THREAD

**Issue by ahryshchanka** [vkhorikov/CSharpFunctionalExtensions#79]
In case OnSuccess return IEnumerable<Result<T>> required to use method:

```
var result = Result.Combine(results);
return result.IsSuccess
         ? Result.Ok(results.Select(e => e.Value))
         : Result.Fail<IEnumerable<T>>(result.Error);
```

and to do it in OnSuccess method:
`.OnSuccess(results => /*code above*/)`

It will be nice to have extension methods:
`Result<IEnumerable<T>> Combine(this IEnumerable<Result<T>> results)`
`Result Combine(this IEnumerable<Result> results)`

In this case we will have something like:
```
.OnSuccess(arg => ... ) /* returns IEnumerable<Result<T>> */
.Combine() /* convert IEnumerable<Result<T>> to Result<IEnumerable<T>> */
.OnSuccess(collection => ... )
```

**Comment by vkhorikov** [comment]
Looks like a good one, please go ahead with a PR.
