### ISSUE TITLE
Create new CSharpFunctionalExtensions asp.net code API specific

### ISSUE THREAD

**Issue by a-z-hub** [vkhorikov/CSharpFunctionalExtensions#84]
Add new project with dependency to CSharpFunctionalExtensions for asp.net code API specific methods. For example for create results based on Result.

@vkhorikov what do you think about it?

**Comment by vkhorikov** [comment]
Could you elaborate? What's the indented use case? Is it for demonstration purposes or to help with asp.net core APIs specifically? Any examples?

**Comment by ahryshchanka** [comment]
It is special extension methods for asp.net core.
I'll create example app with mvp of package and I'll share link.
