### ISSUE TITLE
Result.Ok(...) needs non-null value

### ISSUE THREAD

**Issue by altmann** [vkhorikov/CSharpFunctionalExtensions#89]
Hi, 

I have an use case where I want to put null as value into an Result. The problem is that an ArgumentNullException is thrown if I do that. 

Here is the following use case:

```
    public Result<DateTime?> Validate(DateTime? value)
    {
        // do here some preparations (e.g for strings some trimming)
        var preparedValue = PrepareValue(value);

        // do here some validations
        var validationResult = ValidateValue(preparedValue);

        if(validationResult.IsFailure)
            return Result.Fail(validationResult.Error);
       
        return Result.Ok(preparedValue);
    }
```

If null is passed into the Validate method I want to return these value with null. Null is for me a valid value. I want to return the prepared value because I have to process it further. 

So what I want is Result.Ok(null) without an ArgumentNullException. Do you see any problems changing this behavior in your library?

**Comment by vkhorikov** [comment]
Thanks for the bug report, should be fixed in 1.15.2
