### ISSUE TITLE
Creating a result with null as value (all types, not only nullable struct)

### ISSUE THREAD

**Issue by altmann** [vkhorikov/CSharpFunctionalExtensions#90]
Hi, 

I see you fixed already issue #89 which is about returning Result.Ok<DateTime?>(null). Thanks for that. Why do you only fixed it for nullable structs? I get still an ArgumentException in the following codelines:

```
        class Staat
        {

        }

        static void Main(string[] args)
        {
            var result = Result.Ok<Staat>(null);
            var result2 = Result.Ok<string>(null);
        }
```

It still works not for strings and also not for normal classes. Do you see a chance to fix this so that all types of null can be inserted into an Result?

BTW: Thanks for the great library. 👍

**Comment by vkhorikov** [comment]
Hi Michael,

For non-structs (reference types), I recommend using `Result<Maybe<string>>`. For example:

----
Maybe<string> str = null;
var result = Result.Ok<Maybe<string>>(str);

var result = Result.Ok<Maybe<string>>(Maybe<string>.None);
----

**Comment by altmann** [comment]
I knew you would say that. :)

But in my string use case the null value semantically doesn't mean an absence of the value. The null string value here in my use case is a valid value and is comparable with other valid values like "Michael or "H". 

Therefore I would prefer returning a simple null value instead of a maybe. In my domain null is not a special value so i don't want handle it explicitly with maybe. 

Iam not sure if the library csharpfunctionalextensions should force such an hard constraint (returning null in result is not allowed) because I want to use this library in each domain in many different use cases. 

Do you understand my scenario? Do you see a chance to support Result.Ok<string>(null)?

**Comment by vkhorikov** [comment]
That's an interesting use case. But still, I think this could be solved with an introduction of a value object. Especially as you say that `null` has a domain-specific meaning - it's good to write down this meaning explicitly in code. Something like:

```
        CardNumber : ValueObect
        {
                public static readonly CardNumber None = new CardNumber(null);
        }

        static void Main(string[] args)
        {
                var result = Result.Ok(CardNumber.None);
        }
```

**Comment by altmann** [comment]
Ok, I understand that that null lead to edge cases. I try to describe our use case so that you understand that. We coded a simple ValidationEngine which we used within our ValueObjects because we have very often the same ValidationRules. The ValidationEngine is very generic (for reference types and for structs, nullable structs) and we also want to use Results within the ValidationEngine because we like the pattern. 

`ValidationRule` is a delegate and represents a validation rule like MaxLength, Required, etc. 
`Preparation` is a delegate and represents logic to prepare the value which should be validated. For example trimming a string, etc. 
Preparation can return null values and this is completly valid for us. Therefore the variable `preparedValue` can be null. We want to return this variable within a Result to the consumer of the ValidationEngine. If `preparedValue` is null then we get an Exception from your library. 

```
    public static class ValidationEngine
    {
        public static Result<TValue> Execute<TValue>(TValue value, string label, IEnumerable<ValidationRule<TValue>> validationRules, IEnumerable<Preparation<TValue>> preparations)
        {

            var preparedValue = PrepareValue(value, preparations);

            var validationResult = ValidateValue(preparedValue, label, validationRules);

            return validationResult.IsFailure
                       ? Result.Fail<TValue>(validationResult.Error)
                       : Result.Ok<TValue>(preparedValue);
        }

        private static TValue PrepareValue<TValue>(TValue unpreparedValue, IEnumerable<Preparation<TValue>> preparations)
        {
            var preparedValue = unpreparedValue;

            foreach (var preperation in preparations)
            {
                preparedValue = preperation(preparedValue);
            }

            return preparedValue;
        }

        private static Result ValidateValue<TValue>(TValue value, string label, IEnumerable<ValidationRule<TValue>> validationRules)
        {
            var results = new List<Result>();

            foreach (var validationRule in validationRules)
            {
                results.Add(validationRule(value, label));
            }

            return results.ToCombinedResult();
        }
    }
```

Our actual workaround is that we introduce an ValidationEngineResultWrapper which is a class with one property of Type TValue. So we can write: `Result.Ok<ValidationEngineResultWrapper<TValue>(new ValidationEngineResultWrapper(preparedValue));` The property Value of the Result class is never null and we can set the property of ValidationEngineResultWrapper easily to null without throwing an exception. It is not the nicest solution but it works. 

So if you don't change your mind and you don't support such an scenario then please close the issue.

**Comment by vkhorikov** [comment]
That does make sense. I'm removing the validation and pushing a new version (1.16.0)

**Comment by altmann** [comment]
Thank you very much for supporting our use case and implementing this feature. :)
