### ISSUE TITLE
ValueObject Equals throws Exception

### ISSUE THREAD

**Issue by linkdotnet** [vkhorikov/CSharpFunctionalExtensions#93]
What is the reason behind throwing an exception if the types of two ValueObjects don't match?
As stated by [MSDN about Object.Equals](https://docs.microsoft.com/en-us/dotnet/api/system.object.equals?view=netframework-4.7.2): 

> Implementations of Equals must not throw exceptions; they should always return a value. For example, if obj is null, the Equals method should return false instead of throwing an ArgumentNullException.

I would propse just to return false. If you want I can create a PR.

**Comment by vkhorikov** [comment]
Yes, I'm familiar with this implementation, and `ValueObject` had this implementation initially. I'm going back-and-forth on this issue, actually. The idea behind throwing an exception was that Value Objects are a special case. If you compare 2 value objects of different types, it always means there's a bug in the code, hence the code should fail fast.

Recently, I found a counter-example to this guideline, though, so need to revert this logic back to MS's canonical implementation, indeed.

Please, go ahead with the PR. Thanks.

**Comment by linkdotnet** [comment]
As stated in the PR. There are cases where comparing different `ValueObject` of different types can be the case. Newtonsoft.Json uses `Equals` to determine circular references.
Yes it is arguable if serializing ValueObjects is not an anti-pattern itself and furthermore if using `Object.Equals` is the right way for determining circular references.

**Comment by vkhorikov** [comment]
Published in 1.16.1, closing the issue
