### ISSUE TITLE
Replace hash code implementation with the use of HashCode

### ISSUE THREAD

**Issue by vkhorikov** [vkhorikov/CSharpFunctionalExtensions#94]
Need to replace the manual hash code calculation in `ValueObject` (generated with the help of Resharper) to the use of the new HashCode class from .NET Core: https://docs.microsoft.com/en-us/dotnet/api/system.hashcode?view=netcore-2.1

**Comment by ahryshchanka** [comment]
`HashCode` available only in .net core 2.1 2.2, for .net standard * it unavailable and can't be implemented, possibly after extend `System.Runtime.dll`
